// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhP9V8WsdoGjVwUp-q1K_s3Mmdgc6BQJc',
    appId: '1:176813042326:web:bf26fe2dae58b8e5cbf0b7',
    messagingSenderId: '176813042326',
    projectId: 'aiemojie',
    authDomain: 'aiemojie.firebaseapp.com',
    storageBucket: 'aiemojie.firebasestorage.app',
    measurementId: 'G-GKC3HE057T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG1rW8bt5Sxktkl4gGxuPT2_tjAPdUrfQ',
    appId: '1:176813042326:android:9b24ecc0b0a63c10cbf0b7',
    messagingSenderId: '176813042326',
    projectId: 'aiemojie',
    storageBucket: 'aiemojie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4XIJTeNlQmJux1LwNPunE0WtjEEadUQ',
    appId: '1:176813042326:ios:a9b1c5f6893c1530cbf0b7',
    messagingSenderId: '176813042326',
    projectId: 'aiemojie',
    storageBucket: 'aiemojie.firebasestorage.app',
    iosBundleId: 'as.emojimaker.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4XIJTeNlQmJux1LwNPunE0WtjEEadUQ',
    appId: '1:176813042326:ios:a9b1c5f6893c1530cbf0b7',
    messagingSenderId: '176813042326',
    projectId: 'aiemojie',
    storageBucket: 'aiemojie.firebasestorage.app',
    iosBundleId: 'com.example.aiImageMakerr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhP9V8WsdoGjVwUp-q1K_s3Mmdgc6BQJc',
    appId: '1:176813042326:web:7abeza397ebdfcfb8cbf0b7',
    messagingSenderId: '176813042326',
    projectId: 'aiemojie',
    authDomain: 'aiemojie.firebaseapp.com',
    storageBucket: 'aiemojie.firebasestorage.app',
    measurementId: 'G-MEXL7BCJ3Z',
  );
}
