import 'package:get/get.dart';

class AppTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI Prompt Emoji',
      'describeEmojiHint': 'Describe your emoji....',
      'selectStyleTitle': 'Select a Style',
      'discoverTitle': 'Discover',
      'requestTimeout': 'Request Timeout',
      "wordLimitReached": "Word limit reached",
      "wordLimitExceeded": "Word limit exceeded",
      "pastedTextTrimmed": "Text trimmed to fit limit",
      "textPasted": "Text pasted successfully",
      "alreadyPremium": "Already Premium!",
      "youAreAlreadyAPremiumUser":
          "You are already a premium user. Enjoy all features!",
      "goToHome": "Go to Home",
      "premium": "Premium",
      "noPreviousPurchasesFound": "No previous purchases found",

      'pro': 'Pro',
      'noInternet': 'No Internet Connection.',
      'nohistoryyet': 'No History Yet',
      'createyourfirstemojiorsticker':
          'Once you make your first emoji, it will appear here. Let’s get creative!',
      'generating': 'Generating...',
      'share': 'Share',
      'download': 'Download',
      'stickerdialog': 'Sticker Dialog',
      'loadingemojis': 'Loading Emojis...',
      "all": "All",
      "delete": "Delete",
      "stickers": "Stickers",
      "preview": "Preview",
      "please_select_image_first": "Please select an image first",
      "minimal": "minimal",
      'enter_prompt': 'Please enter a prompt',

      // BUTTONS
      'paste': 'Paste',
      'generate': 'Generate',
      'Rate_Us': 'Rate Us',

      "Worst_Title": "Something Went Wrong?",
      "Poor_Title": "Not Quite There",
      "Average_Title": "Room for Improvement",
      "Good_Title": "Glad you Liked it!",
      "Super_Title": "Are you Awesome!",
      "Worst_Description":
          "We're really sorry to hear that. our feedback ca help us improve . Tell us what ddn't work for you.",
      "Poor_Description":
          "We're on a journey to do better. Let us know what  felt off, and we'll work on it",
      "Average_Description":
          "Thanks for the honest rating! We'd love to know what could've made your experince better.",
      "Good_Description":
          "We're happy to see a thumbs-up. Got suggestions or ideas? We'd love to nhear them .",
      "Super_Description":
          "Tha ks for the love! Your supprt keeps us going . Want to help others by leaving a review ?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Text pasted from clipboard!',
      'noTextInClipboard': 'No text found in clipboard',
      'speechPermission': 'Microphone permission is required',
      'speechNotAvailable': 'Speech recognition not available',
      'noSpeechDetected': 'No speech detected. Microphone turned off.',
      "network_error": "Network error. Please check your connection.",
      "request_timeout": "Request timeout. Please try again.",
      "invalid_response_format": "Invalid response format",
      "no_url_found": "No URL found in response",

      // STYLES
      'styleClassic': 'Classic',
      'styleCartoon': 'Cartoon',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Line Art',
      'imagetoemoji': 'Image to Emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Beaming Smile',
      'emojiCowboyHat': 'Cowboy Hat',
      'emojiSunglassesSmile': 'Sunglasses Smile',
      'emojiGrinning': 'Grinning',
      'emojiWinking': 'Winking',
      'emojiLaughing': 'Laughing',
      'uploadOrChooseImageToBegin': 'Upload or Choose Image to Begin',
      'supports': 'Supports: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Select a Style',
      'prompt': 'Prompt',
      'optional': '(optional)',
      'typeYourPromptHere': 'Type your prompt here',
      'myEmojis': 'My Emojis',
      'skip': 'Skip',
      'getStarted': 'Get Started',
      'continue': 'Continue',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Smiling face emoji with smiling eyes facing right.',
      'generated': 'Generated',
      'purchasesRestoredSuccessfully': 'Purchases restored successfully!',
      'inAppPurchasesNotAvailable':
          "In-app purchases are not available on this device.",
      'ok': 'OK',
      'error': 'Error',
      'success': 'Success',
      'upgradeToPremium': 'Upgrade to Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Enjoy unlimited emoji creations and\n exclusive features.',
      'unlimitedEmojiGeneration': 'Unlimited Emoji Generation',
      'highQualityConversions': 'High Quality Conversions',
      'noAdvertisements': 'No Advertisements',
      'startFreeTrial': 'Start Free Trial',
      'weekly': 'Weekly',
      'flexibleAccess': 'Flexible Access',
      'loading': 'Loading...',
      'yearly': 'Yearly',
      'bestValue': 'Best Value',
      'threeDaysFreeTrial': '3 Days Free Trial',
      'securePayment': 'Secure Payment',
      'processing': 'Processing...',
      'privacy': 'Privacy Policy',
      'restore': 'Restore',
      'terms': 'Terms of use',
      'permissionDenied': 'Permission denied!',
      'savedToGallery': 'Saved to gallery!',
      'failedToSave': 'Failed to save!',
      'result': 'Result',
      'regenerate': 'Regenerate',
      'home': 'Home',
      'discover': 'Discover',
      'settings': 'Settings',
      'explainEmoji': 'Explain Emoji',
      'describeAndGetClearUniqueEmojis':
          'Describe and get clear & unique emojis.',
      'imageToEmoji': 'Image to Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Upload any image and convert it into a fun emoji',
      'createSticker': 'Create Sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Turn your photos into stickers for social media.',
      'recent': 'Recent',
      'viewAll': 'View All',
      'noRecentEmojisYet': 'No recent emojis yet',
      'beamingSmile': 'Beaming Smile',
      'preferences': 'Preferences',
      'language': 'Languages',
      'appTheme': 'App Theme',
      'helpAndSupport': 'Help & Support',
      'contactus': 'Contact Us',
      'feedback': 'Feedback',
      'rateTheApp': 'Rate the App',
      'restorePurchase': 'Restore Purchase',
      'legal': 'Legal',
      'privacyPolicy': 'Privacy Policy',
      'termsAndConditions': 'Terms & Conditions',
      'inviteFriends': 'Invite Friends',
      'shareApp': 'Share App',
      'aiEmojiMaker': 'AI Emoji Maker',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Upload a Photo to Convert into a Sticker',
    },
    'en_GB': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI Prompt Emoji',
      'describeEmojiHint': 'Describe your emoji...',
      'selectStyleTitle': 'Select a Style',
      'discoverTitle': 'Discover',
      'pro': 'Pro',
      "all": "All",
      "delete": "Delete",
      'requestTimeout': 'Request Timeout',
      "wordLimitReached": "Word limit reached",
      "wordLimitExceeded": "Word limit exceeded",
      "pastedTextTrimmed": "Text trimmed to fit limit",
      "textPasted": "Text pasted successfully",
      "stickers": "Stickers",
      "preview": "Preview",
      "emojis": "Emojis",
      "pastel": "Pastel",
      "minimal": "Minimal",
      "no_commitment": "No commitment, cancel anytime",
      "trial_info": "3 days free trial then pay",
      "please_select_image_first": "Please select an image first",
      "minimal": "Minimal",
      'enter_prompt': 'Please enter a prompt',
      "noPreviousPurchasesFound": "No previous purchases found",

      // BUTTONS
      'paste': 'Paste',
      'generate': 'Generate',

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Text pasted from clipboard!',
      'noTextInClipboard': 'No text found in clipboard',
      'speechPermission': 'Microphone permission is required',
      'speechNotAvailable': 'Speech recognition not available',
      'noSpeechDetected': 'No speech detected. Microphone turned off.',
      "network_error": "Network error. Please check your connection.",
      "request_timeout": "Request timed out. Please try again.",
      "invalid_response_format": "Invalid response format",
      "no_url_found": "No URL found in the response",
      "share": "Share",
      "download": "Download",
      "stickerdialog": "Sticker Dialog",
      "loadingemojis": "Loading Emojis...",
      "createyourfirstemojiorsticker":
          "Once you make your first emoji, it will appear here. Let’s get creative!",
      "nohistoryyet": "No History Yet",
      "noInternet": "No Internet Connection.",

      // STYLES
      'styleClassic': 'Classic',
      'styleCartoon': 'Cartoon',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Line Art',
      'imagetoemoji': 'Image to Emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Beaming Smile',
      'emojiCowboyHat': 'Cowboy Hat',
      'emojiSunglassesSmile': 'Sunglasses Smile',
      'emojiGrinning': 'Grinning',
      'emojiWinking': 'Winking',
      'emojiLaughing': 'Laughing',
      'uploadOrChooseImageToBegin': 'Upload or Choose Image to Begin',
      'supports': 'Supports: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Select a Style',
      'prompt': 'Prompt',
      'optional': '(optional)',
      'typeYourPromptHere': 'Type your prompt here',
      'myEmojis': 'My Emojis',
      'skip': 'Skip',
      'getStarted': 'Get Started',
      'continue': 'Continue',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Smiling face emoji with smiling eyes facing right.',
      'generated': 'Generated',
      'purchasesRestoredSuccessfully': 'Purchases restored successfully!',
      'inAppPurchasesNotAvailable':
          'In-app purchases are not available on this device.',
      'ok': 'OK',
      'error': 'Error',
      'success': 'Success',
      'upgradeToPremium': 'Upgrade to Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Enjoy unlimited emoji creations and\n exclusive features.',
      'unlimitedEmojiGeneration': 'Unlimited Emoji Generation',
      'highQualityConversions': 'High-quality Conversions',
      'noAdvertisements': 'No Advertisements',
      'startFreeTrial': 'Start Free Trial',
      'weekly': 'Weekly',
      'flexibleAccess': 'Flexible Access',
      'loading': 'Loading...',
      'yearly': 'Yearly',
      'bestValue': 'Best Value',
      'threeDaysFreeTrial': '3 Days Free Trial',
      'securePayment': 'Secure Payment',
      'processing': 'Processing...',
      'privacy': 'Privacy policy',
      'restore': 'Restore',
      'terms': 'Terms of use',
      'permissionDenied': 'Permission denied!',
      'savedToGallery': 'Saved to gallery!',
      'failedToSave': 'Failed to save!',
      'result': 'Result',
      'regenerate': 'Regenerate',
      'home': 'Home',
      'discover': 'Discover',
      'settings': 'Settings',
      'explainEmoji': 'Explain Emoji',
      'describeAndGetClearUniqueEmojis':
          'Describe and get clear & unique emojis.',
      'imageToEmoji': 'Image to Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Upload any image and convert it into a fun emoji',
      'createSticker': 'Create Sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Turn your photos into stickers for social media.',
      'recent': 'Recent',
      'viewAll': 'View All',
      'noRecentEmojisYet': 'No recent emojis yet',
      'beamingSmile': 'Beaming Smile',
      'preferences': 'Preferences',
      'language': 'Languages',
      'appTheme': 'App Theme',
      'helpAndSupport': 'Help & Support',
      'contactus': 'Contact Us',
      'feedback': 'Feedback',
      'rateTheApp': 'Rate the App',
      'restorePurchase': 'Restore Purchase',
      'legal': 'Legal',
      'privacyPolicy': 'Privacy Policy',
      'termsAndConditions': 'Terms & Conditions',
      'inviteFriends': 'Invite Friends',
      'shareApp': 'Share App',
      'aiEmojiMaker': 'AI Emoji Maker',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Upload a photo to convert into a sticker',
    },
    'ar_SA': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'رموز تعبيرية بالذكاء الاصطناعي',
      'describeEmojiHint': 'صف الرمز التعبيري الخاص بك...',
      'selectStyleTitle': 'اختر النمط',
      'discoverTitle': 'اكتشف',
      'enter_prompt': 'الرجاء إدخال الطلب',
      "preferences": "التفضيلات",
      "requestTimeout": "انتهت مهلة الطلب",
      "wordLimitReached": "تم الوصول إلى الحد الأقصى للكلمات",
      "wordLimitExceeded": "تم تجاوز الحد الأقصى للكلمات",
      "pastedTextTrimmed": "تم تقليص النص الملصق ليتوافق مع حد الكلمات",
      "textPasted": "تم لصق النص بنجاح",
      "alreadyPremium": "أنت بالفعل بريميوم!",
      "youAreAlreadyAPremiumUser":
          "أنت بالفعل مستخدم بريميوم. استمتع بجميع الميزات!",
      "goToHome": "اذهب إلى الصفحة الرئيسية",
      "premium": "بريميوم",
      "noPreviousPurchasesFound": "لم يتم العثور على عمليات شراء سابقة",

      'pro': 'برو',
      "all": "الكل",
      "delete": "حذف",
      "stickers": "ملصقات",
      "preview": "معاينة",
      "emojis": "الرموز التعبيرية",
      "pastel": "ألوان الباستيل",
      "minimal": "بسيط",
      "no_commitment": "بدون التزام، ألغِ في أي وقت",
      "trial_info": "تجربة مجانية لمدة 3 أيام ثم الدفع",
      "please_select_image_first": "الرجاء تحديد صورة أولاً",
      "minimal": "الحد الأدنى",

      // BUTTONS
      'paste': 'لصق',
      'generate': 'إنشاء',

      'Rate_Us': 'قيمنا',

      "Worst_Title": "حدث خطأ ما؟",
      "Poor_Title": "ليس مثاليًا",
      "Average_Title": "هناك مجال للتحسين",
      "Good_Title": "سعداء لأنك أعجبتك!",
      "Super_Title": "أنت رائع!",

      "Worst_Description":
          "نأسف لسماع ذلك. يمكن لملاحظاتك مساعدتنا على التحسن. أخبرنا بما لم يعمل بشكل جيد.",
      "Poor_Description":
          "نحن نسعى للتحسن. أخبرنا بما لم يكن على ما يرام، وسنعمل على إصلاحه.",
      "Average_Description":
          "شكرًا على تقييمك الصادق! نود معرفة ما الذي كان يمكن أن يجعل تجربتك أفضل.",
      "Good_Description":
          "سعداء برؤيتك تشير بالإعجاب. هل لديك اقتراحات أو أفكار؟ نود سماعها.",
      "Super_Description":
          "شكرًا على دعمك! دعمك يحفزنا على الاستمرار. هل ترغب بمساعدة الآخرين بترك تقييم؟",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'تم لصق النص من الحافظة!',
      'noTextInClipboard': 'لا يوجد نص في الحافظة',
      'speechPermission': 'مطلوب إذن الميكروفون',
      'speechNotAvailable': 'التعرّف على الصوت غير متاح',
      'noSpeechDetected': 'لم يتم اكتشاف أي صوت. تم إيقاف الميكروفون.',
      "network_error": "خطأ في الشبكة. يرجى التحقق من الاتصال.",
      "request_timeout": "انتهت مهلة الطلب. يرجى المحاولة مرة أخرى.",
      "invalid_response_format": "تنسيق الاستجابة غير صالح",
      "no_url_found": "لم يتم العثور على أي رابط في الاستجابة",
      "share": "مشاركة",
      "download": "تحميل",
      "stickerdialog": "حوار الملصق",
      "loadingemojis": "جارٍ تحميل الرموز التعبيرية...",
      "createyourfirstemojiorsticker": "أنشئ أول رمز تعبيري أو ملصق لك",
      "nohistoryyet": "لا يوجد سجل بعد",
      "noInternet": "لا يوجد اتصال بالإنترنت.",

      // STYLES
      'styleClassic': 'كلاسيكي',
      'styleCartoon': 'كرتوني',
      'stylePixel': 'بكسل',
      'styleLineArt': 'خطوط فنية',
      'imagetoemoji': 'صورة لرمز',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'ابتسامة مشرقة',
      'emojiCowboyHat': 'وجه بقبعة كاوبوي',
      'emojiSunglassesSmile': 'ابتسامة بنظارات شمسية',
      'emojiGrinning': 'ابتسامة عريضة',
      'emojiWinking': 'غمزة',
      'emojiLaughing': 'ضحك',
      'uploadOrChooseImageToBegin': 'قم برفع صورة أو اختيارها للبدء',
      'supports': 'يدعم: PNG، JPG، JPEG، WEBP',
      'selectAStyle': 'اختر نمطًا',
      'prompt': 'الوصف',
      'optional': '(اختياري)',
      'typeYourPromptHere': 'اكتب الوصف هنا',
      'myEmojis': 'رموزي',
      'skip': 'تخطّي',
      'getStarted': 'ابدأ',
      'continue': 'متابعة',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'وجه مبتسم بعيون مبتسمة ينظر إلى اليمين.',
      'generated': 'تم الإنشاء',
      'purchasesRestoredSuccessfully': 'تم استعادة المشتريات بنجاح!',
      'inAppPurchasesNotAvailable':
          'المشتريات داخل التطبيق غير متاحة على هذا الجهاز.',
      'ok': 'حسنًا',
      'error': 'خطأ',
      'success': 'نجاح',
      'upgradeToPremium': 'الترقية إلى بريميوم',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'استمتع بإنشاء عدد غير محدود من الرموز\n التعبيرية وميزات حصرية.',
      'unlimitedEmojiGeneration': 'إنشاء غير محدود للرموز التعبيرية',
      'highQualityConversions': 'تحويلات عالية الجودة',
      'noAdvertisements': 'بدون إعلانات',
      'startFreeTrial': 'ابدأ الفترة التجريبية',
      'weekly': 'أسبوعي',
      'flexibleAccess': 'وصول مرن',
      'loading': 'جارٍ التحميل...',
      'yearly': 'سنوي',
      'bestValue': 'أفضل قيمة',
      'threeDaysFreeTrial': '3 أيام تجريبية مجانية',
      'securePayment': 'دفع آمن',
      'processing': 'جارٍ المعالجة...',
      'privacy': 'الخصوصية',
      'restore': 'استعادة',
      'terms': 'الشروط',
      'permissionDenied': 'تم رفض الإذن!',
      'savedToGallery': 'تم الحفظ في المعرض!',
      'failedToSave': 'فشل في الحفظ!',
      'result': 'النتيجة',
      'regenerate': 'إعادة إنشاء',
      'home': 'الرئيسية',
      'discover': 'اكتشف',
      'settings': 'الإعدادات',
      'explainEmoji': 'شرح الرموز التعبيرية',
      'describeAndGetClearUniqueEmojis':
          'صف واحصل على رموز تعبيرية واضحة وفريدة.',
      'imageToEmoji': 'صورة لرمز',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'قم برفع أي صورة وحولها إلى رمز تعبيري ممتع',
      'createSticker': 'إنشاء ملصق',
      'turnYourPhotosIntoStickersForSocialMedia':
          'حوّل صورك إلى ملصقات لوسائل التواصل الاجتماعي.',
      'recent': 'الأخيرة',
      'viewAll': 'عرض الكل',
      'noRecentEmojisYet': 'لا توجد رموز تعبيرية حديثة بعد',
      'beamingSmile': 'ابتسامة مشرقة',
      'appearances': 'المظهر',
      'language': 'اللغة',
      'appTheme': 'سمة التطبيق',
      'helpAndSupport': 'المساعدة والدعم',
      'contactus': 'اتصل بالدعم',
      'feedback': 'ملاحظات',
      'rateTheApp': 'قيّم التطبيق',
      'restorePurchase': 'استعادة المشتريات',
      'legal': 'قانوني',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsAndConditions': 'الشروط والأحكام',
      'inviteFriends': 'دعوة الأصدقاء',
      'shareApp': 'مشاركة التطبيق',
      'aiEmojiMaker': 'إنشاء الرموز التعبيرية',
      'sticker': 'ملصق',
      'uploadAPhotoToConvertIntoASticker': 'قم برفع صورة لتحويلها إلى ملصق',
    },
    'zh_CN': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI 表情符号生成',
      'describeEmojiHint': '描述你的表情符号...',
      'selectStyleTitle': '选择风格',
      'discoverTitle': '发现',
      'pro': '专业版',
      "all": "全部",
      "delete": "删除",
      "requestTimeout": "请求超时",
      "wordLimitReached": "已达到字数限制",
      "wordLimitExceeded": "已超出字数限制",
      "pastedTextTrimmed": "粘贴的内容已被截断以符合字数限制",
      "textPasted": "文本已成功粘贴",
      "stickers": "贴纸",
      "preview": "预览",
      "emojis": "表情符号",
      "pastel": "柔和色",
      "minimal": "极简",
      "no_commitment": "无需承诺，随时取消",
      "trial_info": "3天免费试用，然后付费",
      "please_select_image_first": "请先选择图片",
      "minimal": "最小",
      'enter_prompt': '请输入提示',
      "alreadyPremium": "已是高级会员！",
      "youAreAlreadyAPremiumUser": "您已经是高级用户。尽情享受所有功能吧！",
      "goToHome": "返回首页",
      "premium": "高级会员",
      "noPreviousPurchasesFound": "未找到以前的购买记录",

      // BUTTONS
      'paste': '粘贴',
      'generate': '生成',
      'Rate_Us': '给我们评分',

      "Worst_Title": "出了点问题？",
      "Poor_Title": "还不够好",
      "Average_Title": "有待改进",
      "Good_Title": "很高兴你喜欢！",
      "Super_Title": "你真棒！",

      "Worst_Description": "很抱歉听到这个。你的反馈可以帮助我们改进。请告诉我们哪里出了问题。",
      "Poor_Description": "我们正在努力做得更好。告诉我们哪里不尽如人意，我们会改进。",
      "Average_Description": "感谢你的真实评分！我们希望了解如何能让你的体验更好。",
      "Good_Description": "很高兴看到你的认可。有什么建议或想法吗？我们很想听听。",
      "Super_Description": "感谢你的支持！你的鼓励让我们前行。想通过留下评价帮助别人吗？",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': '文本已从剪贴板粘贴！',
      'noTextInClipboard': '剪贴板中没有文本',
      'speechPermission': '需要麦克风权限',
      'speechNotAvailable': '语音识别不可用',
      'noSpeechDetected': '未检测到语音。麦克风已关闭。',
      "network_error": "网络错误，请检查您的连接。",
      "request_timeout": "请求超时，请重试。",
      "invalid_response_format": "响应格式无效",
      "no_url_found": "响应中未找到任何 URL",
      "share": "分享",
      "download": "下载",
      "stickerdialog": "贴纸对话框",
      "loadingemojis": "正在加载表情符号...",
      "createyourfirstemojiorsticker": "创建你的第一个表情符号或贴纸",
      "nohistoryyet": "暂无历史记录",
      "noInternet": "无网络连接。",

      // STYLES
      'styleClassic': '经典',
      'styleCartoon': '卡通',
      'stylePixel': '像素',
      'styleLineArt': '线条风格',
      'imagetoemoji': '图片转表情符号',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': '灿烂笑容',
      'emojiCowboyHat': '牛仔帽表情',
      'emojiSunglassesSmile': '墨镜笑脸',
      'emojiGrinning': '咧嘴笑',
      'emojiWinking': '眨眼',
      'emojiLaughing': '大笑',
      'uploadOrChooseImageToBegin': '上传或选择图片开始',
      'supports': '支持：PNG、JPG、JPEG、WEBP',
      'selectAStyle': '选择一种风格',
      'prompt': '提示词',
      'optional': '(可选)',
      'typeYourPromptHere': '在此输入提示词',
      'myEmojis': '我的表情符号',
      'skip': '跳过',
      'getStarted': '开始使用',
      'continue': '继续',
      'smilingFaceEmojiWithSmilingEyesFacingRight': '右侧带笑眼的笑脸表情。',
      'generated': '已生成',
      'purchasesRestoredSuccessfully': '购买恢复成功！',
      'inAppPurchasesNotAvailable': '此设备上无法使用应用内购买。',
      'ok': '确定',
      'error': '错误',
      'success': '成功',
      'upgradeToPremium': '升级到高级版',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures': '享受无限表情符号生成\n以及专属功能。',
      'unlimitedEmojiGeneration': '无限表情生成',
      'highQualityConversions': '高质量转换',
      'noAdvertisements': '无广告',
      'startFreeTrial': '开始免费试用',
      'weekly': '每周',
      'flexibleAccess': '灵活访问',
      'loading': '加载中...',
      'yearly': '每年',
      'bestValue': '最优惠',
      'threeDaysFreeTrial': '3 天免费试用',
      'securePayment': '安全支付',
      'processing': '处理中...',
      'privacy': '隐私',
      'restore': '恢复',
      'terms': '条款',
      'permissionDenied': '权限被拒绝！',
      'savedToGallery': '已保存到相册！',
      'failedToSave': '保存失败！',
      'result': '结果',
      'regenerate': '重新生成',
      'home': '首页',
      'discover': '发现',
      'settings': '设置',
      'explainEmoji': '解释表情符号',
      'describeAndGetClearUniqueEmojis': '描述并获取清晰独特的表情符号。',
      'imageToEmoji': '图片转表情符号',
      'uploadAnyImageAndConvertItIntoAFunEmoji': '上传任意图片转换成有趣的表情符号',
      'createSticker': '创建贴纸',
      'turnYourPhotosIntoStickersForSocialMedia': '将你的照片制作成社交媒体贴纸。',
      'recent': '最近',
      'viewAll': '查看全部',
      'noRecentEmojisYet': '暂无最近表情符号',
      'beamingSmile': '灿烂笑容',
      'Preferences': '外观',
      'language': '语言',
      'appTheme': '应用主题',
      'helpAndSupport': '帮助与支持',
      'contactus': '联系支持',
      'feedback': '反馈',
      'rateTheApp': '为应用评分',
      'restorePurchase': '恢复购买',
      'legal': '法律信息',
      'privacyPolicy': '隐私政策',
      'termsAndConditions': '条款和条件',
      'inviteFriends': '邀请朋友',
      'shareApp': '分享应用',
      'aiEmojiMaker': 'AI 表情符号生成器',
      'sticker': '贴纸',
      'uploadAPhotoToConvertIntoASticker': '上传照片并转换成贴纸',
    },
    'fr_FR': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'Émoji IA',
      'describeEmojiHint': 'Décrivez votre émoji...',
      'selectStyleTitle': 'Choisir un style',
      'discoverTitle': 'Découvrir',
      'pro': 'Pro',
      'enter_prompt': 'Veuillez entrer une invite',
      "alreadyPremium": "Déjà Premium !",
      "youAreAlreadyAPremiumUser":
          "Vous êtes déjà un utilisateur Premium. Profitez de toutes les fonctionnalités !",
      "goToHome": "Aller à l'accueil",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Aucun achat précédent trouvé",

      "all": "Tout",
      "delete": "Supprimer",
      "stickers": "Autocollants",
      "requestTimeout": "Délai de requête dépassé",
      "wordLimitReached": "Limite de mots atteinte",
      "wordLimitExceeded": "Limite de mots dépassée",
      "pastedTextTrimmed":
          "Le texte collé a été tronqué pour respecter la limite de mots",
      "textPasted": "Texte collé avec succès",
      "preview": "Aperçu",
      "emojis": "Émojis",
      "pastel": "Pastel",
      "minimal": "Minimal",
      "no_commitment": "Aucun engagement, annulez à tout moment",
      "trial_info": "3 jours d'essai gratuit puis paiement",
      "please_select_image_first": "Veuillez sélectionner une image d'abord",
      "minimal": "Minimal",
      'Rate_Us': 'Évaluez-nous',

      "Worst_Title": "Quelque chose s'est mal passé ?",
      "Poor_Title": "Pas tout à fait ça",
      "Average_Title": "Des améliorations possibles",
      "Good_Title": "Content que ça vous ait plu !",
      "Super_Title": "Vous êtes génial !",

      "Worst_Description":
          "Nous sommes désolés d'apprendre cela. Vos retours peuvent nous aider à nous améliorer. Dites-nous ce qui n'a pas fonctionné.",
      "Poor_Description":
          "Nous sommes en quête de progrès. Dites-nous ce qui n'allait pas, et nous y travaillerons.",
      "Average_Description":
          "Merci pour votre évaluation honnête ! Nous aimerions savoir ce qui aurait pu améliorer votre expérience.",
      "Good_Description":
          "Nous sommes heureux de voir votre appréciation. Des suggestions ou des idées ? Nous serions ravis de les connaître.",
      "Super_Description":
          "Merci pour votre soutien ! Votre appui nous motive. Voulez-vous aider les autres en laissant un avis ?",

      // BUTTONS
      'paste': 'Coller',
      'generate': 'Générer',

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Texte collé depuis le presse-papiers !',
      'noTextInClipboard': 'Aucun texte trouvé dans le presse-papiers',
      'speechPermission': 'Permission du microphone requise',
      'speechNotAvailable': 'Reconnaissance vocale non disponible',
      'noSpeechDetected': 'Aucun discours détecté. Microphone désactivé.',
      "network_error": "Erreur réseau. Veuillez vérifier votre connexion.",
      "request_timeout": "Délai de la requête dépassé. Veuillez réessayer.",
      "invalid_response_format": "Format de réponse invalide",
      "no_url_found": "Aucune URL trouvée dans la réponse",
      "share": "Partager",
      "download": "Télécharger",
      "stickerdialog": "Dialogue Sticker",
      "loadingemojis": "Chargement des emojis...",
      "createyourfirstemojiorsticker":
          "Créez votre premier emoji ou autocollant",
      "nohistoryyet": "Aucun historique pour le moment",
      "noInternet": "Pas de connexion Internet.",

      // STYLES
      'styleClassic': 'Classique',
      'styleCartoon': 'Animé',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Art linéaire',
      'imagetoemoji': 'Image en émoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Sourire radieux',
      'emojiCowboyHat': 'Chapeau de cow-boy',
      'emojiSunglassesSmile': 'Sourire lunettes de soleil',
      'emojiGrinning': 'Grinçant',
      'emojiWinking': 'Clin d’œil',
      'emojiLaughing': 'Rire',
      'uploadOrChooseImageToBegin': 'Choisissez une image',
      'supports': 'Prend en charge : PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Sélectionnez un style',
      'prompt': 'Prompt',
      'optional': '(facultatif)',
      'typeYourPromptHere': 'Tapez votre prompt ici',
      'myEmojis': 'Mes émojis',
      'skip': 'Passer',
      'getStarted': 'Commencer',
      'continue': 'Continuer',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Émoji visage souriant avec yeux souriants vers la droite.',
      'generated': 'Généré',
      'purchasesRestoredSuccessfully': 'Achats restaurés avec succès !',
      'inAppPurchasesNotAvailable':
          'Les achats intégrés ne sont pas disponibles sur cet appareil.',
      'ok': 'OK',
      'error': 'Erreur',
      'success': 'Succès',
      'upgradeToPremium': 'Passer à Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Profitez de créations illimitées d’émojis et\nde fonctionnalités exclusives.',
      'unlimitedEmojiGeneration': 'Génération illimitée d’émojis',
      'highQualityConversions': 'Conversions haute qualité',
      'noAdvertisements': 'Sans publicités',
      'startFreeTrial': 'Commencer l’essai gratuit',
      'weekly': 'Hebdomadaire',
      'flexibleAccess': 'Accès flexible',
      'loading': 'Chargement...',
      'yearly': 'Annuel',
      'bestValue': 'Meilleur rapport qualité/prix',
      'threeDaysFreeTrial': 'Essai gratuit de 3 jours',
      'securePayment': 'Paiement sécurisé',
      'processing': 'Traitement...',
      'privacy': 'Confidentialité',
      'restore': 'Restaurer',
      'terms': 'Conditions',
      'permissionDenied': 'Permission refusée !',
      'savedToGallery': 'Enregistré dans la galerie !',
      'failedToSave': 'Échec de l’enregistrement !',
      'result': 'Résultat',
      'regenerate': 'Régénérer',
      'home': 'Accueil',
      'discover': 'Découvrir',
      'settings': 'Régl',
      'explainEmoji': 'Expliquer l’émoji',
      'describeAndGetClearUniqueEmojis':
          'Décrivez et obtenez des émojis clairs et uniques.',
      'imageToEmoji': 'Image en émoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Téléversez une image et transformez-la en émoji amusant',
      'createSticker': 'Créer un sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Transformez vos photos en stickers pour les réseaux sociaux.',
      'recent': 'Récent',
      'viewAll': 'Voir tout',
      'noRecentEmojisYet': 'Aucun émoji récent pour le moment',
      'beamingSmile': 'Sourire radieux',
      'preferences': 'Preferences',
      'language': 'Languages',
      'appTheme': 'Thème de l’application',
      'helpAndSupport': 'Aide & Support',
      'contactus': 'Contacter le support',
      'feedback': 'Retour',
      'rateTheApp': 'Évaluer l’application',
      'restorePurchase': 'Restaurer l’achat',
      'legal': 'Légal',
      'privacyPolicy': 'Politique de confidentialité',
      'termsAndConditions': 'Termes et conditions',
      'inviteFriends': 'Inviter des amis',
      'shareApp': 'Partager l’application',
      'aiEmojiMaker': 'Créateur d’émojis IA',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Téléversez une photo pour la transformer en sticker',
    },
    'de_DE': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'KI-Emoji',
      'describeEmojiHint': 'Beschreibe dein Emoji...',
      'selectStyleTitle': 'Stil auswählen',
      'discoverTitle': 'Entdecken',
      'pro': 'Pro',
      "all": "Alle",
      'enter_prompt': 'Bitte geben Sie eine Eingabeaufforderung ein',
      "alreadyPremium": "Bereits Premium!",
      "youAreAlreadyAPremiumUser":
          "Sie sind bereits Premium-Nutzer. Genießen Sie alle Funktionen!",
      "goToHome": "Zur Startseite",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Keine vorherigen Käufe gefunden",

      "delete": "Löschen",
      "stickers": "Aufkleber",
      "preview": "Vorschau",
      "emojis": "Emojis",
      "pastel": "Pastell",
      "minimal": "Minimal",
      "no_commitment": "Keine Verpflichtung, jederzeit kündbar",
      "trial_info": "3 Tage kostenlos testen, danach bezahlen",
      "please_select_image_first": "Bitte zuerst ein Bild auswählen",
      "minimal": "Minimal",

      // BUTTONS
      'paste': 'Einfügen',
      'generate': 'Generieren',
      "Worst_Title": "Etwas ist schiefgelaufen?",
      "Poor_Title": "Nicht ganz richtig",
      "Average_Title": "Verbesserungsbedarf",
      "Good_Title": "Schön, dass es Ihnen gefallen hat!",
      "Super_Title": "Sie sind großartig!",

      "Worst_Description":
          "Es tut uns leid, das zu hören. Ihr Feedback hilft uns, uns zu verbessern. Teilen Sie uns mit, was nicht funktioniert hat.",
      "Poor_Description":
          "Wir sind auf dem Weg, besser zu werden. Lassen Sie uns wissen, was nicht stimmte, und wir werden daran arbeiten.",
      "Average_Description":
          "Danke für Ihre ehrliche Bewertung! Wir würden gerne wissen, wie wir Ihre Erfahrung verbessern könnten.",
      "Good_Description":
          "Wir freuen uns über Ihr positives Feedback. Haben Sie Vorschläge oder Ideen? Wir würden sie gerne hören.",
      "Super_Description":
          "Danke für Ihre Unterstützung! Ihr Zuspruch motiviert uns. Möchten Sie anderen helfen, indem Sie eine Bewertung hinterlassen?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Text aus der Zwischenablage eingefügt!',
      'noTextInClipboard': 'Kein Text in der Zwischenablage gefunden',
      'speechPermission': 'Mikrofonberechtigung erforderlich',
      'speechNotAvailable': 'Spracherkennung nicht verfügbar',
      'noSpeechDetected': 'Keine Sprache erkannt. Mikrofon ausgeschaltet.',
      "network_error": "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung.",
      "request_timeout":
          "Anfragezeit überschritten. Bitte versuchen Sie es erneut.",
      "invalid_response_format": "Ungültiges Antwortformat",
      "no_url_found": "Keine URL in der Antwort gefunden",
      "share": "Teilen",
      "download": "Herunterladen",
      "stickerdialog": "Sticker-Dialog",
      "loadingemojis": "Emojis werden geladen...",
      "createyourfirstemojiorsticker":
          "Erstelle dein erstes Emoji oder Sticker",
      "nohistoryyet": "Noch keine Historie",
      "noInternet": "Keine Internetverbindung.",

      // STYLES
      'styleClassic': 'Klassisch',
      'styleCartoon': 'Cartoon',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Linie',
      'imagetoemoji': 'Bild zu Emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Strahlendes Lächeln',
      'emojiCowboyHat': 'Cowboyhut',
      'emojiSunglassesSmile': 'Sonnenbrillen-Lächeln',
      'emojiGrinning': 'Grinsend',
      'emojiWinking': 'Zwinkernd',
      'emojiLaughing': 'Lachend',
      'uploadOrChooseImageToBegin': 'Bild hochladen',
      'supports': 'Unterstützt: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Wähle einen Stil',
      'prompt': 'Prompt',
      'optional': '(optional)',
      'typeYourPromptHere': 'Gib hier deinen Prompt ein',
      'myEmojis': 'Emojis',
      'skip': 'Überspringen',
      'getStarted': 'Loslegen',
      'continue': 'Fortfahren',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Lächelndes Gesicht mit lächelnden Augen, nach rechts gerichtet.',
      'generated': 'Generiert',
      'purchasesRestoredSuccessfully': 'Käufe erfolgreich wiederhergestellt!',
      'inAppPurchasesNotAvailable':
          'In-App-Käufe sind auf diesem Gerät nicht verfügbar.',
      'ok': 'OK',
      'error': 'Fehler',
      'success': 'Erfolg',
      'upgradeToPremium': 'Auf Premium upgraden',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Genieße unbegrenzte Emoji-Erstellungen und\nexklusive Funktionen.',
      'unlimitedEmojiGeneration': 'Unbegrenzte Emoji-Erstellung',
      'highQualityConversions': 'Hochwertige Konvertierungen',
      'noAdvertisements': 'Keine Werbung',
      'startFreeTrial': 'Kostenlose Testphase starten',
      'weekly': 'Wöchentlich',
      'flexibleAccess': 'Flexibler Zugang',
      'loading': 'Laden...',
      'yearly': 'Jährlich',
      'bestValue': 'Bestes Angebot',
      'threeDaysFreeTrial': '3 Tage kostenlos testen',
      'securePayment': 'Sichere Zahlung',
      'processing': 'Verarbeitung...',
      'privacy': 'Datenschutz',
      'restore': 'Wiederherstellen',
      'terms': 'Bedingungen',
      'permissionDenied': 'Berechtigung verweigert!',
      'savedToGallery': 'In Galerie gespeichert!',
      'failedToSave': 'Speichern fehlgeschlagen!',
      'result': 'Ergebnis',
      'regenerate': 'Erneut generieren',
      'home': 'Startseite',
      'discover': 'Entdecken',
      'settings': 'Prefs',
      'explainEmoji': 'Emoji erklären',
      'describeAndGetClearUniqueEmojis':
          'Beschreibe und erhalte klare & einzigartige Emojis.',
      'imageToEmoji': 'Bild zu Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Lade ein beliebiges Bild hoch und verwandle es in ein lustiges Emoji',
      'createSticker': 'Sticker erstellen',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Verwandle deine Fotos in Sticker für soziale Medien.',
      'recent': 'Kürzlich',
      'viewAll': 'Alle ansehen',
      'noRecentEmojisYet': 'Noch keine kürzlichen Emojis',
      'beamingSmile': 'Strahlendes Lächeln',
      'preferences': 'Erscheinungsbilder',
      'language': 'Sprache',
      'appTheme': 'App-Thema',
      'helpAndSupport': 'Hilfe & Support',
      'contactus': 'Support kontaktieren',
      'feedback': 'Feedback',
      'rateTheApp': 'App bewerten',
      'restorePurchase': 'Kauf wiederherstellen',
      'legal': 'Rechtliches',
      'privacyPolicy': 'Datenschutzrichtlinie',
      'termsAndConditions': 'Allgemeine Geschäftsbedingungen',
      'inviteFriends': 'Freunde einladen',
      'shareApp': 'App teilen',
      'aiEmojiMaker': 'KI Emoji Maker',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Lade ein Foto hoch, um es in einen Sticker zu verwandeln',
    },
    'it_IT': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'Emoji AI',
      'describeEmojiHint': 'Descrivi la tua emoji...',
      'selectStyleTitle': 'Seleziona uno stile',
      'discoverTitle': 'Scopri',
      'pro': 'Pro',
      "all": "Tutti",
      'enter_prompt': 'Per favore inserisci un prompt',

      "delete": "Elimina",
      "stickers": "Adesivi",
      "preview": "Anteprima",
      "emojis": "Emoji",
      "pastel": "Pastello",
      "minimal": "Minimal",
      "no_commitment": "Nessun impegno, annulla in qualsiasi momento",
      "trial_info": "Prova gratuita di 3 giorni, poi paga",
      "please_select_image_first": "Seleziona prima un'immagine",
      "minimal": "Minimale",
      "alreadyPremium": "Già Premium!",
      "youAreAlreadyAPremiumUser":
          "Sei già un utente Premium. Goditi tutte le funzionalità!",
      "goToHome": "Vai alla Home",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Nessun acquisto precedente trovato",

      // BUTTONS
      'paste': 'Incolla',
      'generate': 'Genera',
      'Rate_Us': 'Valutaci',

      "Worst_Title": "Qualcosa è andato storto?",
      "Poor_Title": "Non proprio il massimo",
      "Average_Title": "C'è margine di miglioramento",
      "Good_Title": "Felici che ti sia piaciuto!",
      "Super_Title": "Sei fantastico!",

      "Worst_Description":
          "Ci dispiace sentirlo. Il tuo feedback ci aiuta a migliorare. Dicci cosa non ha funzionato.",
      "Poor_Description":
          "Stiamo cercando di fare meglio. Dicci cosa non ha funzionato e lavoreremo su questo.",
      "Average_Description":
          "Grazie per la valutazione onesta! Ci piacerebbe sapere cosa avrebbe potuto rendere la tua esperienza migliore.",
      "Good_Description":
          "Siamo felici del tuo apprezzamento. Hai suggerimenti o idee? Ci piacerebbe conoscerli.",
      "Super_Description":
          "Grazie per il supporto! Il tuo sostegno ci motiva. Vuoi aiutare gli altri lasciando una recensione?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Testo incollato dagli appunti!',
      'noTextInClipboard': 'Nessun testo trovato negli appunti',
      'speechPermission': 'Permesso microfono richiesto',
      'speechNotAvailable': 'Riconoscimento vocale non disponibile',
      'noSpeechDetected': 'Nessun discorso rilevato. Microfono spento.',
      "network_error": "Errore di rete. Controlla la tua connessione.",
      "request_timeout": "Tempo di richiesta scaduto. Riprova.",
      "invalid_response_format": "Formato della risposta non valido",
      "no_url_found": "Nessun URL trovato nella risposta",
      "share": "Condividi",
      "download": "Scarica",
      "stickerdialog": "Finestra Sticker",
      "loadingemojis": "Caricamento emoji...",
      "createyourfirstemojiorsticker": "Crea la tua prima emoji o sticker",
      "nohistoryyet": "Nessuna cronologia",
      "noInternet": "Nessuna connessione Internet.",

      // STYLES
      'styleClassic': 'Classico',
      'styleCartoon': 'Cartone',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Linee',
      'imagetoemoji': 'Immagine in emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Sorriso raggiante',
      'emojiCowboyHat': 'Cappello da cowboy',
      'emojiSunglassesSmile': 'Sorriso con occhiali da sole',
      'emojiGrinning': 'Sorridente',
      'emojiWinking': 'Occhiolino',
      'emojiLaughing': 'Risata',
      'uploadOrChooseImageToBegin': 'Carica o scegli un’immagine per iniziare',
      'supports': 'Supporta: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Seleziona uno stile',
      'prompt': 'Prompt',
      'optional': '(opzionale)',
      'typeYourPromptHere': 'Digita il tuo prompt qui',
      'myEmojis': 'Mie emoji',
      'skip': 'Salta',
      'getStarted': 'Inizia',
      'continue': 'Continua',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Emoji faccina sorridente con occhi sorridenti rivolti a destra.',
      'generated': 'Generato',
      'purchasesRestoredSuccessfully': 'Acquisti ripristinati con successo!',
      'inAppPurchasesNotAvailable':
          'Gli acquisti in-app non sono disponibili su questo dispositivo.',
      'ok': 'OK',
      'error': 'Errore',
      'success': 'Successo',
      'upgradeToPremium': 'Passa a Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Goditi creazioni illimitate di emoji e\nfunzionalità esclusive.',
      'unlimitedEmojiGeneration': 'Generazione illimitata di emoji',
      'highQualityConversions': 'Conversioni di alta qualità',
      'noAdvertisements': 'Nessuna pubblicità',
      'startFreeTrial': 'Inizia prova gratuita',
      'weekly': 'Settimanale',
      'flexibleAccess': 'Accesso flessibile',
      'loading': 'Caricamento...',
      'yearly': 'Annuale',
      'bestValue': 'Miglior valore',
      'threeDaysFreeTrial': '3 giorni di prova gratuita',
      'securePayment': 'Pagamento sicuro',
      'processing': 'Elaborazione...',
      'privacy': 'Privacy Policy',
      'restore': 'Ripristina',
      'terms': 'Termini',
      'permissionDenied': 'Permesso negato!',
      'savedToGallery': 'Salvato nella galleria!',
      'failedToSave': 'Salvataggio fallito!',
      'result': 'Risultato',
      'regenerate': 'Rigenera',
      'home': 'Home',
      'discover': 'Scopri',
      'settings': 'Impost',
      'explainEmoji': 'Spiega',
      'describeAndGetClearUniqueEmojis':
          'Descrivi e ottieni emoji chiare e uniche.',
      'imageToEmoji': 'Immagine in emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Carica qualsiasi immagine e trasformala in un’emoji divertente',
      'createSticker': 'Crea sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Trasforma le tue foto in sticker per i social media.',
      'recent': 'Recenti',
      'viewAll': 'Visualizza tutto',
      'noRecentEmojisYet': 'Ancora nessuna emoji recente',
      'beamingSmile': 'Sorriso raggiante',
      'preferences': 'Aspetto',
      'language': 'Lingua',
      'appTheme': 'Tema dell’app',
      'helpAndSupport': 'Aiuto & Supporto',
      'contactus': 'Contatta supporto',
      'feedback': 'Feedback',
      'rateTheApp': 'Valuta l’app',
      'restorePurchase': 'Ripristina acquisto',
      'legal': 'Legale',
      'privacyPolicy': 'Politica sulla privacy',
      'termsAndConditions': 'Termini e condizioni',
      'inviteFriends': 'Invita amici',
      'shareApp': 'Condividi app',
      'aiEmojiMaker': 'Creatore di Emoji AI',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Carica una foto per trasformarla in sticker',
    },
    'ja_JP': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI絵文字',
      'describeEmojiHint': '絵文字を説明してください...',
      'selectStyleTitle': 'スタイルを選択',
      'discoverTitle': '発見',
      'pro': 'プロ',
      "all": "すべて",
      'enter_prompt': 'プロンプトを入力してください',

      "delete": "削除",
      "stickers": "ステッカー",
      "preview": "プレビュー",
      "emojis": "絵文字",
      "pastel": "パステル",
      "minimal": "ミニマル",
      "no_commitment": "契約不要、いつでもキャンセル可能",
      "trial_info": "3日間の無料トライアル後に支払い",
      "please_select_image_first": "まず画像を選択してください",
      "minimal": "最小",
      "alreadyPremium": "すでにプレミアムです！",
      "youAreAlreadyAPremiumUser": "あなたはすでにプレミアムユーザーです。すべての機能をお楽しみください！",
      "goToHome": "ホームへ戻る",
      "premium": "プレミアム",
      "noPreviousPurchasesFound": "以前の購入は見つかりませんでした",

      // BUTTONS
      'paste': '貼り付け',
      'generate': '生成',
      'Rate_Us': '評価する',

      "Worst_Title": "問題が発生しましたか？",
      "Poor_Title": "いまいちです",
      "Average_Title": "改善の余地があります",
      "Good_Title": "気に入っていただけて嬉しいです！",
      "Super_Title": "あなたは素晴らしい！",

      "Worst_Description":
          "ご迷惑をおかけして申し訳ありません。フィードバックは改善の助けになります。うまくいかなかった点を教えてください。",
      "Poor_Description": "より良くするために努力しています。問題だった点を教えていただければ、改善に努めます。",
      "Average_Description": "率直な評価ありがとうございます！体験をより良くするにはどうすればよかったか教えてください。",
      "Good_Description": "高評価をいただき嬉しいです。ご提案やアイデアはありますか？ぜひお聞かせください。",
      "Super_Description":
          "サポートありがとうございます！皆さまの応援が私たちの励みです。他の方のためにレビューを残してみませんか？",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'クリップボードからテキストを貼り付けました！',
      'noTextInClipboard': 'クリップボードにテキストが見つかりません',
      'speechPermission': 'マイクの権限が必要です',
      'speechNotAvailable': '音声認識は利用できません',
      'noSpeechDetected': '音声が検出されませんでした。マイクはオフです。',
      "network_error": "ネットワークエラー。接続を確認してください。",
      "request_timeout": "リクエストがタイムアウトしました。再試行してください。",
      "invalid_response_format": "無効なレスポンス形式です",
      "no_url_found": "レスポンスにURLが見つかりません",
      "share": "共有",
      "download": "ダウンロード",
      "stickerdialog": "ステッカーダイアログ",
      "loadingemojis": "絵文字を読み込み中...",
      "createyourfirstemojiorsticker": "最初の絵文字またはステッカーを作成",
      "nohistoryyet": "履歴はまだありません",
      "noInternet": "インターネット接続がありません。",

      // STYLES
      'styleClassic': 'クラシック',
      'styleCartoon': 'アニメ',
      'stylePixel': 'ピクセル',
      'styleLineArt': '線画',
      'imagetoemoji': '画像を絵文字に',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': '輝く笑顔',
      'emojiCowboyHat': 'カウボーイハット',
      'emojiSunglassesSmile': 'サングラス笑顔',
      'emojiGrinning': 'にっこり笑顔',
      'emojiWinking': 'ウィンク',
      'emojiLaughing': '笑い',
      'uploadOrChooseImageToBegin': '画像をアップロードまたは選択して開始',
      'supports': '対応形式: PNG、JPG、JPEG、WEBP',
      'selectAStyle': 'スタイルを選択',
      'prompt': 'プロンプト',
      'optional': '(任意)',
      'typeYourPromptHere': 'ここにプロンプトを入力',
      'myEmojis': 'マイ絵文字',
      'skip': 'スキップ',
      'getStarted': '開始',
      'continue': '続行',
      'smilingFaceEmojiWithSmilingEyesFacingRight': '右を向いた笑顔の目をした絵文字。',
      'generated': '生成済み',
      'purchasesRestoredSuccessfully': '購入が正常に復元されました！',
      'inAppPurchasesNotAvailable': 'このデバイスではアプリ内購入は利用できません。',
      'ok': 'OK',
      'error': 'エラー',
      'success': '成功',
      'upgradeToPremium': 'プレミアムにアップグレード',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          '無制限の絵文字作成と\n限定機能をお楽しみください。',
      'unlimitedEmojiGeneration': '無制限の絵文字生成',
      'highQualityConversions': '高品質変換',
      'noAdvertisements': '広告なし',
      'startFreeTrial': '無料トライアル開始',
      'weekly': '週次',
      'flexibleAccess': '柔軟なアクセス',
      'loading': '読み込み中...',
      'yearly': '年間',
      'bestValue': '最良の価値',
      'threeDaysFreeTrial': '3日間無料トライアル',
      'securePayment': '安全な支払い',
      'processing': '処理中...',
      'privacy': 'プライバシー',
      'restore': '復元',
      'terms': '利用規約',
      'permissionDenied': '許可が拒否されました！',
      'savedToGallery': 'ギャラリーに保存しました！',
      'failedToSave': '保存に失敗しました！',
      'result': '結果',
      'regenerate': '再生成',
      'home': 'ホーム',
      'discover': '発見',
      'settings': '設定',
      'explainEmoji': '絵文字を説明',
      'describeAndGetClearUniqueEmojis': '説明して、明確でユニークな絵文字を取得。',
      'imageToEmoji': '画像を絵文字に',
      'uploadAnyImageAndConvertItIntoAFunEmoji': '任意の画像をアップロードして楽しい絵文字に変換',
      'createSticker': 'ステッカー作成',
      'turnYourPhotosIntoStickersForSocialMedia': '写真をソーシャルメディア用ステッカーに変換。',
      'recent': '最近',
      'viewAll': 'すべて表示',
      'noRecentEmojisYet': '最近の絵文字はありません',
      'beamingSmile': '輝く笑顔',
      'preferences': '外観',
      'language': '言語',
      'appTheme': 'アプリテーマ',
      'helpAndSupport': 'ヘルプ＆サポート',
      'contactus': 'サポートに連絡',
      'feedback': 'フィードバック',
      'rateTheApp': 'アプリを評価',
      'restorePurchase': '購入を復元',
      'legal': '法的情報',
      'privacyPolicy': 'プライバシーポリシー',
      'termsAndConditions': '利用規約',
      'inviteFriends': '友達を招待',
      'shareApp': 'アプリを共有',
      'aiEmojiMaker': 'AI絵文字メーカー',
      'sticker': 'ステッカー',
      'uploadAPhotoToConvertIntoASticker': '写真をアップロードしてステッカーに変換',
    },
    'ko_KR': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI 이모지',
      'describeEmojiHint': '이모지를 설명하세요...',
      'selectStyleTitle': '스타일 선택',
      'discoverTitle': '발견',
      'pro': '프로',
      'enter_prompt': '프롬프트를 입력하세요',

      "all": "전체",
      "delete": "삭제",
      "stickers": "스티커",
      "preview": "미리보기",
      "emojis": "이모지",
      "pastel": "파스텔",
      "minimal": "미니멀",
      "no_commitment": "약정 없음, 언제든 취소 가능",
      "trial_info": "3일 무료 체험 후 결제",
      "please_select_image_first": "먼저 이미지를 선택하세요",
      "minimal": "최소",
      "alreadyPremium": "이미 프리미엄입니다!",
      "youAreAlreadyAPremiumUser": "이미 프리미엄 사용자입니다. 모든 기능을 즐기세요!",
      "goToHome": "홈으로 이동",
      "premium": "프리미엄",
      "noPreviousPurchasesFound": "이전 구매 내역이 없습니다",

      // BUTTONS
      'paste': '붙여넣기',
      'generate': '생성',
      'Rate_Us': '평가하기',
      'Rate_Us': '평가하기',

      "Worst_Title": "문제가 발생했나요?",
      "Poor_Title": "조금 부족해요",
      "Average_Title": "개선이 필요합니다",
      "Good_Title": "마음에 드셨다니 기뻐요!",
      "Super_Title": "정말 멋져요!",

      "Worst_Description":
          "불편을 드려 죄송합니다. 피드백은 저희가 개선하는 데 큰 도움이 됩니다. 무엇이 잘못되었는지 알려주세요.",
      "Poor_Description": "더 나아지기 위해 노력하고 있습니다. 부족했던 부분을 알려주시면 개선하겠습니다.",
      "Average_Description": "솔직한 평가 감사합니다! 경험을 더 좋게 만들 수 있었던 방법을 알려주세요.",
      "Good_Description": "좋아요 표시해주셔서 기쁩니다. 제안이나 아이디어가 있나요? 듣고 싶습니다.",
      "Super_Description":
          "응원 감사합니다! 여러분의 지원이 저희를 계속 나아가게 합니다. 다른 사람을 돕기 위해 리뷰를 남기시겠어요?",

      "Worst_Title": "문제가 발생했나요?",
      "Poor_Title": "조금 부족해요",
      "Average_Title": "개선이 필요합니다",
      "Good_Title": "마음에 드셨다니 기뻐요!",
      "Super_Title": "정말 멋져요!",

      "Worst_Description":
          "불편을 드려 죄송합니다. 여러분의 피드백은 저희가 개선하는 데 도움이 됩니다. 무엇이 잘못되었는지 알려주세요.",
      "Poor_Description": "더 나아지기 위해 노력하고 있습니다. 부족했던 점을 알려주시면 개선하겠습니다.",
      "Average_Description": "솔직한 평가 감사합니다! 경험을 더 좋게 만들 수 있었던 방법을 알려주세요.",
      "Good_Description": "좋아요 표시해주셔서 기쁩니다. 제안이나 아이디어가 있나요? 듣고 싶습니다.",
      "Super_Description":
          "응원 감사합니다! 여러분의 지원이 저희를 움직이게 합니다. 다른 사람을 돕기 위해 리뷰를 남기시겠어요?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': '클립보드에서 텍스트가 붙여넣기되었습니다!',
      'noTextInClipboard': '클립보드에 텍스트가 없습니다',
      'speechPermission': '마이크 권한이 필요합니다',
      'speechNotAvailable': '음성 인식 사용 불가',
      'noSpeechDetected': '음성이 감지되지 않았습니다. 마이크가 꺼져 있습니다.',
      "network_error": "네트워크 오류입니다. 연결을 확인하세요.",
      "request_timeout": "요청 시간이 초과되었습니다. 다시 시도하세요.",
      "invalid_response_format": "잘못된 응답 형식입니다.",
      "no_url_found": "응답에서 URL을 찾을 수 없습니다.",
      "share": "공유",
      "download": "다운로드",
      "stickerdialog": "스티커 대화창",
      "loadingemojis": "이모지 로딩 중...",
      "createyourfirstemojiorsticker": "첫 번째 이모지 또는 스티커 만들기",
      "nohistoryyet": "아직 기록이 없습니다",
      "noInternet": "인터넷 연결이 없습니다.",

      // STYLES
      'styleClassic': '클래식',
      'styleCartoon': '만화',
      'stylePixel': '픽셀',
      'styleLineArt': '라인 아트',
      'imagetoemoji': '이미지 → 이모지',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': '환한 미소',
      'emojiCowboyHat': '카우보이 모자',
      'emojiSunglassesSmile': '선글라스 미소',
      'emojiGrinning': '활짝 웃는 얼굴',
      'emojiWinking': '윙크',
      'emojiLaughing': '웃음',
      'uploadOrChooseImageToBegin': '시작하려면 이미지 업로드 또는 선택',
      'supports': '지원 형식: PNG, JPG, JPEG, WEBP',
      'selectAStyle': '스타일 선택',
      'prompt': '프롬프트',
      'optional': '(선택)',
      'typeYourPromptHere': '여기에 프롬프트 입력',
      'myEmojis': '내 이모지',
      'skip': '건너뛰기',
      'getStarted': '시작하기',
      'continue': '계속',
      'smilingFaceEmojiWithSmilingEyesFacingRight': '오른쪽을 바라보는 웃는 눈의 이모지 얼굴.',
      'generated': '생성됨',
      'purchasesRestoredSuccessfully': '구매가 성공적으로 복원되었습니다!',
      'inAppPurchasesNotAvailable': '이 장치에서는 인앱 구매를 사용할 수 없습니다.',
      'ok': '확인',
      'error': '오류',
      'success': '성공',
      'upgradeToPremium': '프리미엄으로 업그레이드',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          '무제한 이모지 생성과\n독점 기능을 즐기세요.',
      'unlimitedEmojiGeneration': '무제한 이모지 생성',
      'highQualityConversions': '고품질 변환',
      'noAdvertisements': '광고 없음',
      'startFreeTrial': '무료 체험 시작',
      'weekly': '주간',
      'flexibleAccess': '유연한 접근',
      'loading': '로딩 중...',
      'yearly': '연간',
      'bestValue': '최고 가치',
      'threeDaysFreeTrial': '3일 무료 체험',
      'securePayment': '안전 결제',
      'processing': '처리 중...',
      'privacy': '개인정보',
      'restore': '복원',
      'terms': '약관',
      'permissionDenied': '권한이 거부되었습니다!',
      'savedToGallery': '갤러리에 저장됨!',
      'failedToSave': '저장 실패!',
      'result': '결과',
      'regenerate': '다시 생성',
      'home': '홈',
      'discover': '발견',
      'settings': '설정',
      'explainEmoji': '이모지 설명',
      'describeAndGetClearUniqueEmojis': '설명하고 명확하고 독창적인 이모지를 얻으세요.',
      'imageToEmoji': '이미지를 이모지로',
      'uploadAnyImageAndConvertItIntoAFunEmoji': '이미지를 업로드하여 재미있는 이모지로 변환',
      'createSticker': '스티커 만들기',
      'turnYourPhotosIntoStickersForSocialMedia': '사진을 소셜 미디어용 스티커로 변환.',
      'recent': '최근',
      'viewAll': '모두 보기',
      'noRecentEmojisYet': '최근 이모지가 없습니다',
      'beamingSmile': '환한 미소',
      'preferences': '외형',
      'language': '언어',
      'appTheme': '앱 테마',
      'helpAndSupport': '도움말 & 지원',
      'contactus': '지원 문의',
      'feedback': '피드백',
      'rateTheApp': '앱 평가',
      'restorePurchase': '구매 복원',
      'legal': '법적 정보',
      'privacyPolicy': '개인정보 처리방침',
      'termsAndConditions': '이용 약관',
      'inviteFriends': '친구 초대',
      'shareApp': '앱 공유',
      'aiEmojiMaker': 'AI 이모지 메이커',
      'sticker': '스티커',
      'uploadAPhotoToConvertIntoASticker': '사진을 업로드하여 스티커로 변환',
    },
    'pt_PT': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'Emoji IA',
      'describeEmojiHint': 'Descreve o teu emoji...',
      'selectStyleTitle': 'Seleciona um estilo',
      'discoverTitle': 'Descobrir',
      'pro': 'Pro',
      "share": "Partilhar",
      "download": "Descarregar",
      "stickerdialog": "Diálogo de Sticker",
      "loadingemojis": "A carregar emojis...",
      'enter_prompt': 'Por favor, insira um prompt',
      "alreadyPremium": "Já é Premium!",
      "youAreAlreadyAPremiumUser":
          "Já é um utilizador Premium. Aproveite todas as funcionalidades!",
      "goToHome": "Ir para a página inicial",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Nenhuma compra anterior encontrada",

      "createyourfirstemojiorsticker": "Crie o seu primeiro emoji ou sticker",
      "nohistoryyet": "Ainda não há histórico",
      "noInternet": "Sem ligação à Internet.",
      "all": "Todos",
      "delete": "Eliminar",
      "stickers": "Autocolantes",
      "preview": "Pré-visualizar",
      "emojis": "Emojis",
      "pastel": "Pastel",
      "minimal": "Minimal",
      "no_commitment": "Sem compromisso, cancele a qualquer momento",
      "trial_info": "3 dias de teste gratuito, depois pague",
      "please_select_image_first": "Por favor, selecione primeiro uma imagem",
      "minimal": "Mínimo",

      'Rate_Us': 'Avalie-nos',

      "Worst_Title": "Algo correu mal?",
      "Poor_Title": "Não está muito bem",
      "Average_Title": "Há margem para melhorar",
      "Good_Title": "Ficamos felizes que tenha gostado!",
      "Super_Title": "Você é incrível!",

      "Worst_Description":
          "Lamentamos ouvir isso. O seu feedback pode ajudar-nos a melhorar. Diga-nos o que não funcionou.",
      "Poor_Description":
          "Estamos a tentar melhorar. Diga-nos o que correu mal e vamos trabalhar nisso.",
      "Average_Description":
          "Obrigado pela avaliação honesta! Gostaríamos de saber como poderíamos tornar a sua experiência melhor.",
      "Good_Description":
          "Ficamos felizes pelo seu feedback positivo. Tem sugestões ou ideias? Adoraríamos ouvi-las.",
      "Super_Description":
          "Obrigado pelo seu apoio! O seu incentivo mantém-nos motivados. Quer ajudar outros deixando uma avaliação?",

      // BUTTONS
      'paste': 'Colar',
      'generate': 'Gerar',

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Texto colado a partir da área de transferência!',
      'noTextInClipboard': 'Nenhum texto encontrado na área de transferência',
      'speechPermission': 'Permissão do microfone necessária',
      'speechNotAvailable': 'Reconhecimento de voz indisponível',
      'noSpeechDetected': 'Nenhuma voz detetada. Microfone desligado.',
      "network_error": "Erro de rede. Verifique a sua ligação.",
      "request_timeout":
          "Tempo de pedido esgotado. Por favor, tente novamente.",
      "invalid_response_format": "Formato de resposta inválido",
      "no_url_found": "Nenhum URL encontrado na resposta",

      // STYLES
      'styleClassic': 'Clássico',
      'styleCartoon': 'Animado',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Linear',
      'imagetoemoji': 'Imagem para Emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Sorriso radiante',
      'emojiCowboyHat': 'Chapéu de cowboy',
      'emojiSunglassesSmile': 'Sorriso com óculos de sol',
      'emojiGrinning': 'Sorridente',
      'emojiWinking': 'Piscadela',
      'emojiLaughing': 'Riso',
      'uploadOrChooseImageToBegin': 'Carregar imagem',
      'supports': 'Suporta: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Seleciona um estilo',
      'prompt': 'Prompt',
      'optional': '(opcional)',
      'typeYourPromptHere': 'Escreve o teu prompt aqui',
      'myEmojis': 'Meus Emojis',
      'skip': 'Ignorar',
      'getStarted': 'Começar',
      'continue': 'Continuar',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Rosto sorridente com olhos sorridentes virados para a direita.',
      'generated': 'Gerado',
      'purchasesRestoredSuccessfully': 'Compras restauradas com sucesso!',
      'inAppPurchasesNotAvailable':
          'As compras dentro da app não estão disponíveis neste dispositivo.',
      'ok': 'OK',
      'error': 'Erro',
      'success': 'Sucesso',
      'upgradeToPremium': 'Atualizar para Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Desfruta de criações ilimitadas de emojis e\nfuncionalidades exclusivas.',
      'unlimitedEmojiGeneration': 'Geração ilimitada de emojis',
      'highQualityConversions': 'Conversões de alta qualidade',
      'noAdvertisements': 'Sem anúncios',
      'startFreeTrial': 'Iniciar teste gratuito',
      'weekly': 'Semanal',
      'flexibleAccess': 'Acesso flexível',
      'loading': 'A carregar...',
      'yearly': 'Anual',
      'bestValue': 'Melhor valor',
      'threeDaysFreeTrial': 'Teste gratuito de 3 dias',
      'securePayment': 'Pagamento seguro',
      'processing': 'A processar...',
      'privacy': 'Privacidade',
      'restore': 'Restaurar',
      'terms': 'Termos',
      'permissionDenied': 'Permissão negada!',
      'savedToGallery': 'Guardado na galeria!',
      'failedToSave': 'Falha ao guardar!',
      'result': 'Resultado',
      'regenerate': 'Regenerar',
      'home': 'Início',
      'discover': 'Descobrir',
      'settings': 'Defs',
      'explainEmoji': 'Explicar Emoji',
      'describeAndGetClearUniqueEmojis':
          'Descreve e obtém emojis claros e únicos.',
      'imageToEmoji': 'Imagem para Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Carrega qualquer imagem e converte-a num emoji divertido',
      'createSticker': 'Criar Sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Transforma as tuas fotos em stickers para redes sociais.',
      'recent': 'Recentes',
      'viewAll': 'Ver todos',
      'noRecentEmojisYet': 'Ainda sem emojis recentes',
      'beamingSmile': 'Sorriso radiante',
      'preferences': 'Aparências',
      'language': 'Idioma',
      'appTheme': 'Tema da App',
      'helpAndSupport': 'Ajuda & Suporte',
      'contactus': 'Contactar Suporte',
      'feedback': 'Feedback',
      'rateTheApp': 'Avaliar App',
      'restorePurchase': 'Restaurar compra',
      'legal': 'Legal',
      'privacyPolicy': 'Política de Privacidade',
      'termsAndConditions': 'Termos e Condições',
      'inviteFriends': 'Convidar Amigos',
      'shareApp': 'Partilhar App',
      'aiEmojiMaker': 'Criador de Emojis IA',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Carrega uma foto para a converter num sticker',
    },
    'ru_RU': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI Эмодзи',
      'describeEmojiHint': 'Опишите ваш эмодзи...',
      'selectStyleTitle': 'Выберите стиль',
      'discoverTitle': 'Открыть',
      'pro': 'Премиум',
      "all": "Все",
      'enter_prompt': 'Пожалуйста, введите запрос',

      "delete": "Удалить",
      "stickers": "Стикеры",
      "preview": "Предпросмотр",
      "emojis": "Эмодзи",
      "pastel": "Пастель",
      "minimal": "Минимализм",
      "no_commitment": "Без обязательств, отмена в любое время",
      "trial_info": "3 дня бесплатного пробного периода, затем оплата",
      "please_select_image_first": "Пожалуйста, сначала выберите изображение",
      "minimal": "Минимальный",
      "alreadyPremium": "Уже Премиум!",
      "youAreAlreadyAPremiumUser":
          "Вы уже являетесь пользователем Премиум. Наслаждайтесь всеми функциями!",
      "goToHome": "На главную",
      "premium": "Премиум",
      "noPreviousPurchasesFound": "Предыдущие покупки не найдены",

      // BUTTONS
      'paste': 'Вставить',
      'generate': 'Создать',
      'Rate_Us': 'Оцените нас',

      "Worst_Title": "Что-то пошло не так?",
      "Poor_Title": "Не совсем хорошо",
      "Average_Title": "Есть что улучшить",
      "Good_Title": "Рады, что вам понравилось!",
      "Super_Title": "Вы потрясающий!",

      "Worst_Description":
          "Нам очень жаль это слышать. Ваш отзыв поможет нам стать лучше. Расскажите, что пошло не так.",
      "Poor_Description":
          "Мы стремимся стать лучше. Сообщите нам, что не понравилось, и мы будем работать над этим.",
      "Average_Description":
          "Спасибо за честную оценку! Нам интересно узнать, что могло бы сделать ваш опыт лучше.",
      "Good_Description":
          "Рады видеть ваш положительный отзыв. Есть предложения или идеи? Мы хотели бы их услышать.",
      "Super_Description":
          "Спасибо за поддержку! Ваша помощь мотивирует нас. Хотите помочь другим, оставив отзыв?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Текст вставлен из буфера обмена!',
      'noTextInClipboard': 'В буфере обмена нет текста',
      'speechPermission': 'Требуется доступ к микрофону',
      'speechNotAvailable': 'Распознавание речи недоступно',
      'noSpeechDetected': 'Речь не обнаружена. Микрофон выключен.',
      "network_error": "Ошибка сети. Пожалуйста, проверьте подключение.",
      "request_timeout": "Время запроса истекло. Попробуйте ещё раз.",
      "invalid_response_format": "Неверный формат ответа",
      "no_url_found": "В ответе не найден URL",
      "share": "Поделиться",
      "download": "Скачать",
      "stickerdialog": "Диалог стикера",
      "loadingemojis": "Загрузка эмодзи...",
      "createyourfirstemojiorsticker": "Создайте свой первый эмодзи или стикер",
      "nohistoryyet": "История отсутствует",
      "noInternet": "Нет подключения к интернету.",

      // STYLES
      'styleClassic': 'Классический',
      'styleCartoon': 'Мульт',
      'stylePixel': 'Пиксельный',
      'styleLineArt': 'Линейный',
      'imagetoemoji': 'Эмодзи',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Сияющая улыбка',
      'emojiCowboyHat': 'Ковбойская шляпа',
      'emojiSunglassesSmile': 'Улыбка в солнцезащитных очках',
      'emojiGrinning': 'Широкая улыбка',
      'emojiWinking': 'Подмигивание',
      'emojiLaughing': 'Смех',
      'uploadOrChooseImageToBegin': 'Выберите изображение',
      'supports': 'Поддержка: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Выберите стиль',
      'prompt': 'Подсказка',
      'optional': '(необязательно)',
      'typeYourPromptHere': 'Введите вашу подсказку здесь',
      'myEmojis': 'Мои эмодзи',
      'skip': 'Пропустить',
      'getStarted': 'Начать',
      'continue': 'Продолжить',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Смайлик с улыбающимися глазами, смотрящий вправо.',
      'generated': 'Создано',
      'purchasesRestoredSuccessfully': 'Покупки успешно восстановлены!',
      'inAppPurchasesNotAvailable':
          'Встроенные покупки недоступны на этом устройстве.',
      'ok': 'ОК',
      'error': 'Ошибка',
      'success': 'Успех',
      'upgradeToPremium': 'Обновить до Премиум',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Наслаждайтесь неограниченным созданием эмодзи и\nэксклюзивными функциями.',
      'unlimitedEmojiGeneration': 'Неограниченное создание эмодзи',
      'highQualityConversions': 'Конвертация высокого качества',
      'noAdvertisements': 'Без рекламы',
      'startFreeTrial': 'Начать бесплатный пробный период',
      'weekly': 'Еженедельно',
      'flexibleAccess': 'Гибкий доступ',
      'loading': 'Загрузка...',
      'yearly': 'Ежегодно',
      'bestValue': 'Лучшая цена',
      'threeDaysFreeTrial': '3-дневный бесплатный пробный период',
      'securePayment': 'Безопасная оплата',
      'processing': 'Обработка...',
      'privacy': 'Конфиденциальность',
      'restore': 'Восстановить',
      'terms': 'Условия',
      'permissionDenied': 'Разрешение отклонено!',
      'savedToGallery': 'Сохранено в галерее!',
      'failedToSave': 'Не удалось сохранить!',
      'result': 'Результат',
      'regenerate': 'Перегенерировать',
      'home': 'Главная',
      'discover': 'Открыть',
      'settings': 'Настр',
      'explainEmoji': 'Объяснить эмодзи',
      'describeAndGetClearUniqueEmojis':
          'Опишите и получите чёткие и уникальные эмодзи.',
      'imageToEmoji': 'Изображение в эмодзи',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Загрузите любое изображение и преобразуйте его в забавный эмодзи',
      'createSticker': 'Создать стикер',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Преобразуйте свои фотографии в стикеры для социальных сетей.',
      'recent': 'Недавние',
      'viewAll': 'Просмотреть все',
      'noRecentEmojisYet': 'Недавних эмодзи пока нет',
      'beamingSmile': 'Сияющая улыбка',
      'preferences': 'Внешний вид',
      'language': 'Язык',
      'appTheme': 'Тема приложения',
      'helpAndSupport': 'Помощь и поддержка',
      'contactus': 'Связаться с поддержкой',
      'feedback': 'Обратная связь',
      'rateTheApp': 'Оценить приложение',
      'restorePurchase': 'Восстановить покупку',
      'legal': 'Правовая информация',
      'privacyPolicy': 'Политика конфиденциальности',
      'termsAndConditions': 'Условия и положения',
      'inviteFriends': 'Пригласить друзей',
      'shareApp': 'Поделиться приложением',
      'aiEmojiMaker': 'Создатель AI Эмодзи',
      'sticker': 'Стикер',
      'uploadAPhotoToConvertIntoASticker':
          'Загрузите фото, чтобы преобразовать его в стикер',
    },
    'es_ES': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'Emoji IA',
      'describeEmojiHint': 'Describe tu emoji...',
      'selectStyleTitle': 'Selecciona un estilo',
      'discoverTitle': 'Descubrir',
      'pro': 'Pro',
      "all": "Todos",
      'enter_prompt': 'Por favor, introduce un mensaje',
      "alreadyPremium": "¡Ya eres Premium!",
      "youAreAlreadyAPremiumUser":
          "Ya eres un usuario Premium. ¡Disfruta de todas las funciones!",
      "goToHome": "Ir al inicio",
      "premium": "Premium",

      "delete": "Eliminar",
      "stickers": "Pegatinas",
      "preview": "Vista previa",
      "emojis": "Emojis",
      "pastel": "Pastel",
      "minimal": "Minimal",
      "no_commitment": "Sin compromiso, cancela en cualquier momento",
      "trial_info": "Prueba gratuita de 3 días, luego paga",
      "please_select_image_first": "Por favor, selecciona primero una imagen",
      "minimal": "Mínimo",

      // BUTTONS
      'paste': 'Pegar',
      'generate': 'Generar',
      'Rate_Us': 'Califícanos',

      "Worst_Title": "¿Algo salió mal?",
      "Poor_Title": "No es del todo correcto",
      "Average_Title": "Hay margen de mejora",
      "Good_Title": "¡Nos alegra que te haya gustado!",
      "Super_Title": "¡Eres increíble!",

      "Worst_Description":
          "Lamentamos escuchar eso. Tus comentarios nos ayudan a mejorar. Cuéntanos qué no funcionó.",
      "Poor_Description":
          "Estamos en un camino de mejora. Cuéntanos qué no estuvo bien y trabajaremos en ello.",
      "Average_Description":
          "Gracias por tu valoración honesta. Nos gustaría saber qué podría haber hecho tu experiencia mejor.",
      "Good_Description":
          "Nos alegra ver tu aprobación. ¿Tienes sugerencias o ideas? Nos encantaría escucharlas.",
      "Super_Description":
          "¡Gracias por tu apoyo! Tu ayuda nos motiva a seguir adelante. ¿Quieres ayudar a otros dejando una reseña?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': '¡Texto pegado desde el portapapeles!',
      'noTextInClipboard': 'No se encontró texto en el portapapeles',
      'speechPermission': 'Se requiere permiso de micrófono',
      'speechNotAvailable': 'Reconocimiento de voz no disponible',
      'noSpeechDetected': 'No se detectó voz. Micrófono apagado.',
      "network_error": "Error de red. Por favor, comprueba tu conexión.",
      "request_timeout":
          "Tiempo de solicitud agotado. Por favor, inténtalo de nuevo.",
      "invalid_response_format": "Formato de respuesta inválido",
      "no_url_found": "No se encontró ninguna URL en la respuesta",
      "share": "Compartir",
      "download": "Descargar",
      "stickerdialog": "Diálogo de Pegatina",
      "loadingemojis": "Cargando emojis...",
      "createyourfirstemojiorsticker": "Crea tu primer emoji o sticker",
      "nohistoryyet": "Aún no hay historial",
      "noInternet": "Sin conexión a Internet.",

      // STYLES
      'styleClassic': 'Clásico',
      'styleCartoon': 'Dibujo animado',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Arte lineal',
      'imagetoemoji': 'Imagen a Emoji',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Sonrisa radiante',
      'emojiCowboyHat': 'Sombrero de vaquero',
      'emojiSunglassesSmile': 'Sonrisa con gafas de sol',
      'emojiGrinning': 'Sonriente',
      'emojiWinking': 'Guiño',
      'emojiLaughing': 'Risa',
      'uploadOrChooseImageToBegin': 'Sube o elige una imagen para comenzar',
      'supports': 'Compatibilidad: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Selecciona un estilo',
      'prompt': 'Prompt',
      'optional': '(opcional)',
      'typeYourPromptHere': 'Escribe tu prompt aquí',
      'myEmojis': 'Mis Emojis',
      'skip': 'Saltar',
      'getStarted': 'Comenzar',
      'continue': 'Continuar',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Emoji de cara sonriente con ojos sonrientes mirando a la derecha.',
      'generated': 'Generado',
      'purchasesRestoredSuccessfully': '¡Compras restauradas con éxito!',
      'inAppPurchasesNotAvailable':
          'Las compras dentro de la app no están disponibles en este dispositivo.',
      'ok': 'OK',
      'error': 'Error',
      'success': 'Éxito',
      'upgradeToPremium': 'Actualizar a Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Disfruta de creaciones ilimitadas de emojis y\nfunciones exclusivas.',
      'unlimitedEmojiGeneration': 'Generación ilimitada de emojis',
      'highQualityConversions': 'Conversiones de alta calidad',
      'noAdvertisements': 'Sin anuncios',
      'startFreeTrial': 'Comenzar prueba gratuita',
      'weekly': 'Semanal',
      'flexibleAccess': 'Acceso flexible',
      'loading': 'Cargando...',
      'yearly': 'Anual',
      'bestValue': 'Mejor valor',
      'threeDaysFreeTrial': 'Prueba gratuita de 3 días',
      'securePayment': 'Pago seguro',
      'processing': 'Procesando...',
      'privacy': 'Privacidad',
      'restore': 'Restaurar',
      'terms': 'Términos',
      'permissionDenied': '¡Permiso denegado!',
      'savedToGallery': '¡Guardado en la galería!',
      'failedToSave': '¡Error al guardar!',
      'result': 'Resultado',
      'regenerate': 'Regenerar',
      'home': 'Inicio',
      'discover': 'Descubrir',
      'settings': 'Ajustes',
      'explainEmoji': 'Explicar Emoji',
      'describeAndGetClearUniqueEmojis':
          'Describe y obtén emojis claros y únicos.',
      'imageToEmoji': 'Imagen a Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Sube cualquier imagen y conviértela en un emoji divertido',
      'createSticker': 'Crear Sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Convierte tus fotos en stickers para redes sociales.',
      'recent': 'Recientes',
      'viewAll': 'Ver todos',
      'noRecentEmojisYet': 'Aún no hay emojis recientes',
      'beamingSmile': 'Sonrisa radiante',
      'preferences': 'Apariencias',
      'language': 'Idioma',
      'appTheme': 'Tema de la app',
      'helpAndSupport': 'Ayuda & Soporte',
      'contactus': 'Contactar soporte',
      'feedback': 'Feedback',
      'rateTheApp': 'Calificar la app',
      'restorePurchase': 'Restaurar compra',
      'legal': 'Legal',
      'privacyPolicy': 'Política de privacidad',
      'termsAndConditions': 'Términos y condiciones',
      'inviteFriends': 'Invitar amigos',
      'shareApp': 'Compartir app',
      'aiEmojiMaker': 'Creador de Emojis IA',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Sube una foto para convertirla en un sticker',
    },
    'th_TH': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI อีโมจิ',
      'describeEmojiHint': 'อธิบายอีโมจิของคุณ....',
      'selectStyleTitle': 'เลือกสไตล์',
      'discoverTitle': 'ค้นหา',
      'enter_prompt': 'กรุณากรอกคำสั่ง',
      "alreadyPremium": "เป็นพรีเมียมแล้ว!",
      "youAreAlreadyAPremiumUser":
          "คุณเป็นผู้ใช้พรีเมียมแล้ว สนุกกับทุกฟีเจอร์ได้เลย!",
      "goToHome": "ไปหน้าหลัก",
      "premium": "พรีเมียม",
      "noPreviousPurchasesFound": "ไม่พบการซื้อก่อนหน้านี้",

      'pro': 'โปร',
      "all": "ทั้งหมด",
      "delete": "ลบ",
      "stickers": "สติกเกอร์",
      "preview": "ตัวอย่าง",
      "emojis": "อิโมจิ",
      "pastel": "พาสเทล",
      "minimal": "เรียบง่าย",
      "no_commitment": "ไม่ผูกมัด ยกเลิกได้ทุกเวลา",
      "trial_info": "ทดลองใช้ฟรี 3 วัน จากนั้นชำระเงิน",
      "please_select_image_first": "กรุณาเลือกภาพก่อน",
      "minimal": "น้อยที่สุด",
      'Rate_Us': 'ให้คะแนนเรา',

      "Worst_Title": "เกิดข้อผิดพลาดหรือไม่?",
      "Poor_Title": "ยังไม่ดีพอ",
      "Average_Title": "มีสิ่งที่ต้องปรับปรุง",
      "Good_Title": "ดีใจที่คุณชอบ!",
      "Super_Title": "คุณสุดยอด!",

      "Worst_Description":
          "เราขอโทษที่ได้ยินเรื่องนี้ ข้อเสนอแนะของคุณช่วยให้เราปรับปรุงได้ แจ้งให้เราทราบว่ามีอะไรผิดพลาดบ้าง",
      "Poor_Description":
          "เรากำลังพยายามทำให้ดีขึ้น แจ้งให้เราทราบว่ามีจุดใดที่ไม่เหมาะสม เราจะปรับปรุง",
      "Average_Description":
          "ขอบคุณสำหรับการให้คะแนนอย่างตรงไปตรงมา เราอยากรู้ว่ามีอะไรที่สามารถทำให้ประสบการณ์ของคุณดียิ่งขึ้นได้",
      "Good_Description":
          "ดีใจที่เห็นคุณชอบ มีคำแนะนำหรือไอเดียไหม? เราอยากฟัง",
      "Super_Description":
          "ขอบคุณสำหรับการสนับสนุนของคุณ! การสนับสนุนของคุณช่วยให้เราก้าวต่อไป คุณอยากช่วยผู้อื่นโดยการรีวิวไหม?",

      // BUTTONS
      'paste': 'วาง',
      'generate': 'สร้าง',

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'วางข้อความจากคลิปบอร์ดแล้ว!',
      'noTextInClipboard': 'ไม่พบข้อความในคลิปบอร์ด',
      'speechPermission': 'ต้องการสิทธิ์เข้าถึงไมโครโฟน',
      'speechNotAvailable': 'ไม่สามารถใช้การรู้จำเสียงพูดได้',
      'noSpeechDetected': 'ไม่พบเสียงพูด ไมโครโฟนถูกปิดแล้ว',
      "network_error": "เกิดข้อผิดพลาดเครือข่าย โปรดตรวจสอบการเชื่อมต่อของคุณ",
      "request_timeout": "หมดเวลาการร้องขอ โปรดลองอีกครั้ง",
      "invalid_response_format": "รูปแบบการตอบกลับไม่ถูกต้อง",
      "no_url_found": "ไม่พบ URL ในการตอบกลับ",
      "share": "แชร์",
      "download": "ดาวน์โหลด",
      "stickerdialog": "กล่องโต้ตอบสติกเกอร์",
      "loadingemojis": "กำลังโหลดอีโมจิ...",
      "createyourfirstemojiorsticker": "สร้างอีโมจิหรือสติกเกอร์แรกของคุณ",
      "nohistoryyet": "ยังไม่มีประวัติ",
      "noInternet": "ไม่มีการเชื่อมต่ออินเทอร์เน็ต",

      // STYLES
      'styleClassic': 'คลาสสิก',
      'styleCartoon': 'การ์ตูน',
      'stylePixel': 'พิกเซล',
      'styleLineArt': 'เส้นกราฟิก',
      'imagetoemoji': 'รูปเป็นอีโมจิ',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'รอยยิ้มสดใส',
      'emojiCowboyHat': 'หมวกคาวบอย',
      'emojiSunglassesSmile': 'รอยยิ้มใส่แว่นกันแดด',
      'emojiGrinning': 'ยิ้มกว้าง',
      'emojiWinking': 'ยักคิ้ว',
      'emojiLaughing': 'หัวเราะ',
      'uploadOrChooseImageToBegin': 'อัปโหลดหรือเลือกภาพเพื่อเริ่มต้น',
      'supports': 'รองรับ: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'เลือกสไตล์',
      'prompt': 'ข้อความแนะนำ',
      'optional': '(ไม่บังคับ)',
      'typeYourPromptHere': 'พิมพ์ข้อความแนะนำที่นี่',
      'myEmojis': 'อีโมจิของฉัน',
      'skip': 'ข้าม',
      'getStarted': 'เริ่มต้น',
      'continue': 'ต่อไป',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'อีโมจิหน้าสีหน้ายิ้มพร้อมดวงตายิ้มหันไปทางขวา',
      'generated': 'สร้างแล้ว',
      'purchasesRestoredSuccessfully': 'กู้คืนการซื้อเรียบร้อยแล้ว!',
      'inAppPurchasesNotAvailable': 'ไม่สามารถใช้การซื้อในแอปบนอุปกรณ์นี้',
      'ok': 'ตกลง',
      'error': 'ข้อผิดพลาด',
      'success': 'สำเร็จ',
      'upgradeToPremium': 'อัปเกรดเป็นพรีเมียม',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'เพลิดเพลินกับการสร้างอีโมจิไม่จำกัดและ\nฟีเจอร์พิเศษ',
      'unlimitedEmojiGeneration': 'สร้างอีโมจิไม่จำกัด',
      'highQualityConversions': 'แปลงคุณภาพสูง',
      'noAdvertisements': 'ไม่มีโฆษณา',
      'startFreeTrial': 'เริ่มทดลองใช้ฟรี',
      'weekly': 'รายสัปดาห์',
      'flexibleAccess': 'เข้าถึงได้อย่างยืดหยุ่น',
      'loading': 'กำลังโหลด...',
      'yearly': 'รายปี',
      'bestValue': 'คุ้มค่าที่สุด',
      'threeDaysFreeTrial': 'ทดลองใช้ฟรี 3 วัน',
      'securePayment': 'การชำระเงินปลอดภัย',
      'processing': 'กำลังประมวลผล...',
      'privacy': 'ความเป็นส่วนตัว',
      'restore': 'กู้คืน',
      'terms': 'ข้อกำหนด',
      'permissionDenied': 'ไม่ได้รับอนุญาต!',
      'savedToGallery': 'บันทึกลงในแกลเลอรีแล้ว!',
      'failedToSave': 'บันทึกล้มเหลว!',
      'result': 'ผลลัพธ์',
      'regenerate': 'สร้างใหม่',
      'home': 'หน้าแรก',
      'discover': 'ค้นหา',
      'settings': 'การตั้งค่า',
      'explainEmoji': 'อธิบายอีโมจิ',
      'describeAndGetClearUniqueEmojis':
          'อธิบายและรับอีโมจิที่ชัดเจนและไม่ซ้ำใคร',
      'imageToEmoji': 'รูปเป็นอีโมจิ',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'อัปโหลดภาพใดก็ได้และเปลี่ยนเป็นอีโมจิสนุก ๆ',
      'createSticker': 'สร้างสติกเกอร์',
      'turnYourPhotosIntoStickersForSocialMedia':
          'เปลี่ยนรูปของคุณเป็นสติกเกอร์สำหรับโซเชียลมีเดีย',
      'recent': 'ล่าสุด',
      'viewAll': 'ดูทั้งหมด',
      'noRecentEmojisYet': 'ยังไม่มีอีโมจิล่าสุด',
      'beamingSmile': 'รอยยิ้มสดใส',
      'preferences': 'ลักษณะ',
      'language': 'ภาษา',
      'appTheme': 'ธีมแอป',
      'helpAndSupport': 'ช่วยเหลือ & สนับสนุน',
      'contactus': 'ติดต่อสนับสนุน',
      'feedback': 'ข้อเสนอแนะ',
      'rateTheApp': 'ให้คะแนนแอป',
      'restorePurchase': 'กู้คืนการซื้อ',
      'legal': 'กฎหมาย',
      'privacyPolicy': 'นโยบายความเป็นส่วนตัว',
      'termsAndConditions': 'ข้อกำหนดและเงื่อนไข',
      'inviteFriends': 'เชิญเพื่อน',
      'shareApp': 'แชร์แอป',
      'aiEmojiMaker': 'ผู้สร้าง AI อีโมจิ',
      'sticker': 'สติกเกอร์',
      'uploadAPhotoToConvertIntoASticker':
          'อัปโหลดรูปเพื่อเปลี่ยนเป็นสติกเกอร์',
    },
    'tr_TR': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'AI Emoji Oluşturucu',
      'describeEmojiHint': 'Emoji\'nizi tanımlayın....',
      'selectStyleTitle': 'Bir Stil Seçin',
      'discoverTitle': 'Keşfet',
      'enter_prompt': 'Lütfen bir istem girin',
      "alreadyPremium": "Zaten Premium!",
      "youAreAlreadyAPremiumUser":
          "Zaten bir Premium kullanıcısınız. Tüm özelliklerin tadını çıkarın!",
      "goToHome": "Ana Sayfaya Git",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Önceki satın alımlar bulunamadı",

      'pro': 'Pro',
      "all": "Tümü",
      "delete": "Sil",
      "stickers": "Çıkartmalar",
      "preview": "Önizleme",
      "emojis": "Emojiler",
      "pastel": "Pastel",
      "minimal": "Minimal",
      "no_commitment": "Taahhütsüz, istediğiniz zaman iptal edin",
      "trial_info": "3 gün ücretsiz deneme, ardından ödeme",
      "please_select_image_first": "Lütfen önce bir resim seçin",
      "minimal": "Minimal",

      // BUTTONS
      'paste': 'Yapıştır',
      'generate': 'Oluştur',
      'Rate_Us': 'Bizi Değerlendir',

      "Worst_Title": "Bir şeyler yanlış mı gitti?",
      "Poor_Title": "Tam olarak değil",
      "Average_Title": "Geliştirme Alanı Var",
      "Good_Title": "Beğenmene sevindik!",
      "Super_Title": "Sen harikasın!",

      "Worst_Description":
          "Bunu duyduğumuza üzüldük. Geri bildiriminiz bizim gelişmemize yardımcı olur. Ne yanlış gittiğini bize bildirin.",
      "Poor_Description":
          "Daha iyi olmak için çalışıyoruz. Eksik olan noktaları bize söyleyin, üzerinde çalışacağız.",
      "Average_Description":
          "Dürüst değerlendirmeniz için teşekkürler! Deneyiminizi daha iyi yapmak için neler yapabileceğimizi bilmek isteriz.",
      "Good_Description":
          "Beğendiğinizi görmek bizi mutlu etti. Öneri veya fikirleriniz var mı? Duymak isteriz.",
      "Super_Description":
          "Desteğiniz için teşekkürler! Sizin desteğiniz bizi motive ediyor. Başkalarına yardımcı olmak için bir yorum bırakmak ister misiniz?",

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Metin panodan yapıştırıldı!',
      'noTextInClipboard': 'Panoda metin bulunamadı',
      'speechPermission': 'Mikrofon izni gerekli',
      'speechNotAvailable': 'Konuşma tanıma kullanılamıyor',
      'noSpeechDetected': 'Konuşma algılanamadı. Mikrofon kapalı.',
      "network_error": "Ağ hatası. Lütfen bağlantınızı kontrol edin.",
      "request_timeout": "İstek süresi doldu. Lütfen tekrar deneyin.",
      "invalid_response_format": "Geçersiz yanıt formatı",
      "no_url_found": "Yanıt içinde URL bulunamadı",
      "share": "Paylaş",
      "download": "İndir",
      "stickerdialog": "Sticker Diyaloğu",
      "loadingemojis": "Emojiler yükleniyor...",
      "createyourfirstemojiorsticker":
          "İlk emojinizi veya stickerınızı oluşturun",
      "nohistoryyet": "Henüz geçmiş yok",
      "noInternet": "İnternet bağlantısı yok.",

      // STYLES
      'styleClassic': 'Klasik',
      'styleCartoon': 'Çizgi Film',
      'stylePixel': 'Piksel',
      'styleLineArt': 'Çizgi Sanatı',
      'imagetoemoji': 'Çevir',

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Parlayan Gülümseme',
      'emojiCowboyHat': 'Kovboy Şapkası',
      'emojiSunglassesSmile': 'Güneş Gözlüklü Gülümseme',
      'emojiGrinning': 'Sırıtma',
      'emojiWinking': 'Göz Kırpma',
      'emojiLaughing': 'Kahkaha',
      'uploadOrChooseImageToBegin': 'Resim seçin',
      'supports': 'Desteklenen formatlar: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Bir stil seçin',
      'prompt': 'İpucu',
      'optional': '(isteğe bağlı)',
      'typeYourPromptHere': 'İpucunuzu buraya yazın',
      'myEmojis': 'Emojim',
      'skip': 'Atla',
      'getStarted': 'Başla',
      'continue': 'Devam Et',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Sağa bakan gülümseyen gözlere sahip gülen yüz emojisi.',
      'generated': 'Oluşturuldu',
      'purchasesRestoredSuccessfully': 'Satın almalar başarıyla geri yüklendi!',
      'inAppPurchasesNotAvailable':
          'Bu cihazda uygulama içi satın alımlar kullanılamıyor.',
      'ok': 'Tamam',
      'error': 'Hata',
      'success': 'Başarılı',
      'upgradeToPremium': 'Premium\'a Yükselt',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Sınırsız emoji oluşturma ve\nözel özelliklerin keyfini çıkarın.',
      'unlimitedEmojiGeneration': 'Sınırsız Emoji Oluşturma',
      'highQualityConversions': 'Yüksek Kaliteli Dönüşümler',
      'noAdvertisements': 'Reklamsız',
      'startFreeTrial': 'Ücretsiz Denemeye Başla',
      'weekly': 'Haftalık',
      'flexibleAccess': 'Esnek Erişim',
      'loading': 'Yükleniyor...',
      'yearly': 'Yıllık',
      'bestValue': 'En İyi Değer',
      'threeDaysFreeTrial': '3 Günlük Ücretsiz Deneme',
      'securePayment': 'Güvenli Ödeme',
      'processing': 'İşleniyor...',
      'privacy': 'Gizlilik',
      'restore': 'Geri Yükle',
      'terms': 'Şartlar',
      'permissionDenied': 'İzin reddedildi!',
      'savedToGallery': 'Galerie kaydedildi!',
      'failedToSave': 'Kaydedilemedi!',
      'result': 'Sonuç',
      'regenerate': 'Yeniden Oluştur',
      'home': 'Ana',
      'discover': 'Keşfet',
      'settings': 'Ayar',
      'explainEmoji': 'Emojiyi Açıkla',
      'describeAndGetClearUniqueEmojis':
          'Açıklayın ve net ve benzersiz emojiler edinin.',
      'imageToEmoji': 'Emojileştir',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Herhangi bir resmi yükleyin ve eğlenceli bir emojie dönüştürün',
      'createSticker': 'Sticker Oluştur',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Fotoğraflarınızı sosyal medya için sticker\'a dönüştürün.',
      'recent': 'Son',
      'viewAll': 'Tümünü Gör',
      'noRecentEmojisYet': 'Henüz son emoji yok',
      'beamingSmile': 'Parlayan Gülümseme',
      'preferences': 'Görünümler',
      'language': 'Dil',
      'appTheme': 'Uygulama Teması',
      'helpAndSupport': 'Yardım & Destek',
      'contactus': 'Destekle İletişime Geç',
      'feedback': 'Geri Bildirim',
      'rateTheApp': 'Uygulamayı Değerlendir',
      'restorePurchase': 'Satın Almayı Geri Yükle',
      'legal': 'Yasal',
      'privacyPolicy': 'Gizlilik Politikası',
      'termsAndConditions': 'Şartlar ve Koşullar',
      'inviteFriends': 'Arkadaşlarını Davet Et',
      'shareApp': 'Uygulamayı Paylaş',
      'aiEmojiMaker': 'AI Emoji Yapıcı',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Sticker oluşturmak için bir fotoğraf yükleyin',
    },
    'vi_VN': {
      // SCREEN TITLES
      'aiPromptEmojiTitle': 'Emoji AI',
      'describeEmojiHint': 'Mô tả emoji của bạn....',
      'selectStyleTitle': 'Chọn phong cách',
      'discoverTitle': 'Khám phá',
      'pro': 'Pro',
      'enter_prompt': 'Vui lòng nhập lệnh',

      "all": "Tất cả",
      "delete": "Xóa",
      "stickers": "Nhãn dán",
      "preview": "Xem trước",
      "emojis": "Biểu tượng cảm xúc",
      "pastel": "Màu pastel",
      "minimal": "Tối giản",
      "no_commitment": "Không ràng buộc, hủy bất cứ lúc nào",
      "trial_info": "Dùng thử miễn phí 3 ngày, sau đó thanh toán",
      "please_select_image_first": "Vui lòng chọn hình ảnh trước",
      "minimal": "Tối thiểu",
      "alreadyPremium": "Đã là Premium!",
      "youAreAlreadyAPremiumUser":
          "Bạn đã là người dùng Premium. Hãy tận hưởng tất cả các tính năng!",
      "goToHome": "Về Trang Chủ",
      "premium": "Premium",
      "noPreviousPurchasesFound": "Không tìm thấy giao dịch mua trước",

      // BUTTONS
      'paste': 'Dán',
      'generate': 'Tạo',

      // TOASTS / SNACKBAR MESSAGES
      'textPasted': 'Đã dán văn bản từ clipboard!',
      'noTextInClipboard': 'Không tìm thấy văn bản trong clipboard',
      'speechPermission': 'Cần quyền truy cập micro',
      'speechNotAvailable': 'Nhận dạng giọng nói không khả dụng',
      'noSpeechDetected': 'Không phát hiện giọng nói. Micro đã tắt.',
      "network_error": "Lỗi mạng. Vui lòng kiểm tra kết nối của bạn.",
      "request_timeout": "Hết thời gian yêu cầu. Vui lòng thử lại.",
      "invalid_response_format": "Định dạng phản hồi không hợp lệ",
      "no_url_found": "Không tìm thấy URL trong phản hồi",
      "share": "Chia sẻ",
      "download": "Tải về",
      "stickerdialog": "Hộp thoại Sticker",
      "loadingemojis": "Đang tải emoji...",
      "createyourfirstemojiorsticker":
          "Tạo emoji hoặc sticker đầu tiên của bạn",
      "nohistoryyet": "Chưa có lịch sử",
      "noInternet": "Không có kết nối Internet.",

      // STYLES
      'styleClassic': 'Cổ điển',
      'styleCartoon': 'Hoạt hình',
      'stylePixel': 'Pixel',
      'styleLineArt': 'Tranh nét',
      'imagetoemoji': 'Chuyển Emoji',
      'Rate_Us': 'Đánh giá chúng tôi',

      "Worst_Title": "Có vấn đề xảy ra?",
      "Poor_Title": "Chưa hoàn hảo",
      "Average_Title": "Cần cải thiện",
      "Good_Title": "Rất vui vì bạn thích!",
      "Super_Title": "Bạn thật tuyệt!",

      "Worst_Description":
          "Chúng tôi rất tiếc khi nghe điều này. Phản hồi của bạn giúp chúng tôi cải thiện. Hãy cho chúng tôi biết điều gì không ổn.",
      "Poor_Description":
          "Chúng tôi đang nỗ lực để tốt hơn. Hãy cho chúng tôi biết điều gì chưa ổn, chúng tôi sẽ cải thiện.",
      "Average_Description":
          "Cảm ơn bạn đã đánh giá trung thực! Chúng tôi muốn biết điều gì có thể làm trải nghiệm của bạn tốt hơn.",
      "Good_Description":
          "Chúng tôi rất vui khi thấy bạn hài lòng. Có gợi ý hoặc ý tưởng nào không? Chúng tôi rất muốn nghe.",
      "Super_Description":
          "Cảm ơn sự ủng hộ của bạn! Sự hỗ trợ của bạn giúp chúng tôi tiến bước. Bạn có muốn giúp người khác bằng cách để lại đánh giá không?",

      // DISCOVER EMOJIS
      'emojiBeamingSmile': 'Nụ cười rạng rỡ',
      'emojiCowboyHat': 'Mũ cao bồi',
      'emojiSunglassesSmile': 'Nụ cười đeo kính râm',
      'emojiGrinning': 'Cười toe',
      'emojiWinking': 'Nháy mắt',
      'emojiLaughing': 'Cười lớn',
      'uploadOrChooseImageToBegin': 'Tải lên hoặc chọn hình để bắt đầu',
      'supports': 'Hỗ trợ: PNG, JPG, JPEG, WEBP',
      'selectAStyle': 'Chọn phong cách',
      'prompt': 'Gợi ý',
      'optional': '(tùy chọn)',
      'typeYourPromptHere': 'Nhập gợi ý của bạn ở đây',
      'myEmojis': 'Emojis tớ',
      'skip': 'Bỏ qua',
      'getStarted': 'Bắt đầu',
      'continue': 'Tiếp tục',
      'smilingFaceEmojiWithSmilingEyesFacingRight':
          'Emoji mặt cười với mắt cười nhìn sang phải.',
      'generated': 'Đã tạo',
      'purchasesRestoredSuccessfully': 'Khôi phục mua hàng thành công!',
      'inAppPurchasesNotAvailable':
          'Mua hàng trong ứng dụng không khả dụng trên thiết bị này.',
      'ok': 'OK',
      'error': 'Lỗi',
      'success': 'Thành công',
      'upgradeToPremium': 'Nâng cấp Premium',
      'enjoyUnlimitedEmojiCreationsAndExclusiveFeatures':
          'Tận hưởng tạo emoji không giới hạn và\ncác tính năng độc quyền.',
      'unlimitedEmojiGeneration': 'Tạo Emoji không giới hạn',
      'highQualityConversions': 'Chuyển đổi chất lượng cao',
      'noAdvertisements': 'Không quảng cáo',
      'startFreeTrial': 'Bắt đầu dùng thử miễn phí',
      'weekly': 'Hàng tuần',
      'flexibleAccess': 'Truy cập linh hoạt',
      'loading': 'Đang tải...',
      'yearly': 'Hàng năm',
      'bestValue': 'Giá trị tốt nhất',
      'threeDaysFreeTrial': 'Dùng thử miễn phí 3 ngày',
      'securePayment': 'Thanh toán an toàn',
      'processing': 'Đang xử lý...',
      'privacy': 'Quyền riêng tư',
      'restore': 'Khôi phục',
      'terms': 'Điều khoản',
      'permissionDenied': 'Từ chối quyền!',
      'savedToGallery': 'Đã lưu vào thư viện!',
      'failedToSave': 'Lưu thất bại!',
      'result': 'Kết quả',
      'regenerate': 'Tạo lại',
      'home': 'Trang',
      'discover': 'Khám',
      'settings': 'Cài',
      'explainEmoji': 'Giải thích Emoji',
      'describeAndGetClearUniqueEmojis':
          'Mô tả và nhận các emoji rõ ràng & độc đáo.',
      'imageToEmoji': 'Ảnh Emoji',
      'uploadAnyImageAndConvertItIntoAFunEmoji':
          'Tải bất kỳ hình nào lên và chuyển thành emoji vui nhộn',
      'createSticker': 'Tạo Sticker',
      'turnYourPhotosIntoStickersForSocialMedia':
          'Biến ảnh của bạn thành sticker cho mạng xã hội.',
      'recent': 'Gần đây',
      'viewAll': 'Xem tất cả',
      'noRecentEmojisYet': 'Chưa có emoji gần đây',
      'beamingSmile': 'Nụ cười rạng rỡ',
      'preferences': 'Giao diện',
      'language': 'Ngôn ngữ',
      'appTheme': 'Giao diện ứng dụng',
      'helpAndSupport': 'Trợ giúp & Hỗ trợ',
      'contactus': 'Liên hệ hỗ trợ',
      'feedback': 'Phản hồi',
      'rateTheApp': 'Đánh giá ứng dụng',
      'restorePurchase': 'Khôi phục mua hàng',
      'legal': 'Pháp lý',
      'privacyPolicy': 'Chính sách bảo mật',
      'termsAndConditions': 'Điều khoản & Điều kiện',
      'inviteFriends': 'Mời bạn bè',
      'shareApp': 'Chia sẻ ứng dụng',
      'aiEmojiMaker': 'Trình tạo Emoji AI',
      'sticker': 'Sticker',
      'uploadAPhotoToConvertIntoASticker':
          'Tải ảnh lên để chuyển thành sticker',
    },
  };
}
